// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for an authentication provider, including support for
/// [JSON Web Token
/// (JWT)](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32).
public struct AuthProvider: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The unique identifier of the auth provider. It will be referred to by
  /// `AuthRequirement.provider_id`.
  ///
  /// Example: "bookstore_auth".
  public var id: Swift.String = Swift.String()

  /// Identifies the principal that issued the JWT. See
  /// https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-4.1.1
  /// Usually a URL or an email address.
  ///
  /// Example: https://securetoken.google.com
  /// Example: 1234567-compute@developer.gserviceaccount.com
  public var issuer: Swift.String = Swift.String()

  /// URL of the provider's public key set to validate signature of the JWT. See
  /// [OpenID
  /// Discovery](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata).
  /// Optional if the key set document:
  ///  - can be retrieved from
  ///    [OpenID
  ///    Discovery](https://openid.net/specs/openid-connect-discovery-1_0.html)
  ///    of the issuer.
  ///  - can be inferred from the email domain of the issuer (e.g. a Google
  ///  service account).
  ///
  /// Example: https://www.googleapis.com/oauth2/v1/certs
  public var jwksUri: Swift.String = Swift.String()

  /// The list of JWT
  /// [audiences](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-4.1.3).
  /// that are allowed to access. A JWT containing any of these audiences will
  /// be accepted. When this setting is absent, JWTs with audiences:
  ///   - "https://[service.name]/[google.protobuf.Api.name]"
  ///   - "https://[service.name]/"
  /// will be accepted.
  /// For example, if no audiences are in the setting, LibraryService API will
  /// accept JWTs with the following audiences:
  ///   -
  ///   https://library-example.googleapis.com/google.example.library.v1.LibraryService
  ///   - https://library-example.googleapis.com/
  ///
  /// Example:
  ///
  ///     audiences: bookstore_android.apps.googleusercontent.com,
  ///                bookstore_web.apps.googleusercontent.com
  public var audiences: Swift.String = Swift.String()

  /// Redirect URL if JWT token is required but not present or is expired.
  /// Implement authorizationUrl of securityDefinitions in OpenAPI spec.
  public var authorizationUrl: Swift.String = Swift.String()

  /// Defines the locations to extract the JWT.  For now it is only used by the
  /// Cloud Endpoints to store the OpenAPI extension [x-google-jwt-locations]
  /// (https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#x-google-jwt-locations)
  ///
  /// JWT locations can be one of HTTP headers, URL query parameters or
  /// cookies. The rule is that the first match wins.
  ///
  /// If not specified,  default to use following 3 locations:
  ///    1) Authorization: Bearer
  ///    2) x-goog-iap-jwt-assertion
  ///    3) access_token query parameter
  ///
  /// Default locations can be specified as followings:
  ///    jwt_locations:
  ///    - header: Authorization
  ///      value_prefix: "Bearer "
  ///    - header: x-goog-iap-jwt-assertion
  ///    - query: access_token
  public var jwtLocations: [JwtLocation] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `AuthProvider`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuthProvider().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let id = CodingKeys(stringValue: "id")
    static let issuer = CodingKeys(stringValue: "issuer")
    static let jwksUri = CodingKeys(stringValue: "jwksUri")
    static let audiences = CodingKeys(stringValue: "audiences")
    static let authorizationUrl = CodingKeys(stringValue: "authorizationUrl")
    static let jwtLocations = CodingKeys(stringValue: "jwtLocations")

    static let _knownKeys: Set<Swift.String> = [
      "id",
      "issuer",
      "jwksUri",
      "audiences",
      "authorizationUrl",
      "jwtLocations",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .issuer) {
      self.issuer = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .jwksUri) {
      self.jwksUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .audiences) {
      self.audiences = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .authorizationUrl) {
      self.authorizationUrl = value
    }
    if let value = try container.decodeIfPresent([JwtLocation].self, forKey: .jwtLocations) {
      self.jwtLocations = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.issuer, forKey: .issuer)
    try container.encode(self.jwksUri, forKey: .jwksUri)
    try container.encode(self.audiences, forKey: .audiences)
    try container.encode(self.authorizationUrl, forKey: .authorizationUrl)
    try container.encode(self.jwtLocations, forKey: .jwtLocations)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.AuthProvider"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
