// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A backend rule provides configuration for an individual API element.
public struct BackendRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Selects the methods to which this rule applies.
  ///
  /// Refer to [selector][google.api.DocumentationRule.selector] for syntax
  /// details.
  ///
  /// [google.api.DocumentationRule.selector]: <doc:DocumentationRule/selector>
  public var selector: Swift.String = Swift.String()

  /// The address of the API backend.
  ///
  /// The scheme is used to determine the backend protocol and security.
  /// The following schemes are accepted:
  ///
  ///    SCHEME        PROTOCOL    SECURITY
  ///    http://       HTTP        None
  ///    https://      HTTP        TLS
  ///    grpc://       gRPC        None
  ///    grpcs://      gRPC        TLS
  ///
  /// It is recommended to explicitly include a scheme. Leaving out the scheme
  /// may cause constrasting behaviors across platforms.
  ///
  /// If the port is unspecified, the default is:
  /// - 80 for schemes without TLS
  /// - 443 for schemes with TLS
  ///
  /// For HTTP backends, use [protocol][google.api.BackendRule.protocol]
  /// to specify the protocol version.
  ///
  /// [google.api.BackendRule.protocol]: <doc:BackendRule/`protocol`>
  public var address: Swift.String = Swift.String()

  /// The number of seconds to wait for a response from a request. The default
  /// varies based on the request protocol and deployment environment.
  public var deadline: Swift.Double = Swift.Double()

  /// Deprecated, do not use.
  public var minDeadline: Swift.Double = Swift.Double()

  /// The number of seconds to wait for the completion of a long running
  /// operation. The default is no deadline.
  public var operationDeadline: Swift.Double = Swift.Double()

  /// Path translation specifies how to combine the backend address with the
  /// request path in order to produce the appropriate forwarding URL for the
  /// request. See [PathTranslation][google.api.BackendRule.PathTranslation] for
  /// more details.
  ///
  /// [google.api.BackendRule.PathTranslation]: <doc:BackendRule/PathTranslation>
  public var pathTranslation: BackendRule.PathTranslation = BackendRule.PathTranslation()

  /// The protocol used for sending a request to the backend.
  /// The supported values are "http/1.1" and "h2".
  ///
  /// The default value is inferred from the scheme in the
  /// [address][google.api.BackendRule.address] field:
  ///
  ///    SCHEME        PROTOCOL
  ///    http://       http/1.1
  ///    https://      http/1.1
  ///    grpc://       h2
  ///    grpcs://      h2
  ///
  /// For secure HTTP backends (https://) that support HTTP/2, set this field
  /// to "h2" for improved performance.
  ///
  /// Configuring this field to non-default values is only supported for secure
  /// HTTP backends. This field will be ignored for all other backends.
  ///
  /// See
  /// https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids
  /// for more details on the supported values.
  ///
  /// [google.api.BackendRule.address]: <doc:BackendRule/address>
  public var `protocol`: Swift.String = Swift.String()

  /// The map between request protocol and the backend address.
  public var overridesByRequestProtocol: [Swift.String: BackendRule] = [:]

  /// The load balancing policy used for connection to the application backend.
  ///
  /// Defined as an arbitrary string to accomondate custom load balancing
  /// policies supported by the underlying channel, but suggest most users use
  /// one of the standard policies, such as the default, "RoundRobin".
  public var loadBalancingPolicy: Swift.String = Swift.String()

  /// Authentication settings used by the backend.
  ///
  /// These are typically used to provide service management functionality to
  /// a backend served on a publicly-routable URL. The `authentication`
  /// details should match the authentication behavior used by the backend.
  ///
  /// For example, specifying `jwt_audience` implies that the backend expects
  /// authentication via a JWT.
  ///
  /// When authentication is unspecified, the resulting behavior is the same
  /// as `disable_auth` set to `true`.
  ///
  /// Refer to https://developers.google.com/identity/protocols/OpenIDConnect for
  /// JWT ID token.
  public var authentication: OneOf_Authentication? = nil

  /// Initialize a new instance of `BackendRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackendRule().with { $0.selector = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case selector = "selector"
    case address = "address"
    case deadline = "deadline"
    case minDeadline = "minDeadline"
    case operationDeadline = "operationDeadline"
    case pathTranslation = "pathTranslation"
    case jwtAudience = "jwtAudience"
    case disableAuth = "disableAuth"
    case `protocol` = "protocol"
    case overridesByRequestProtocol = "overridesByRequestProtocol"
    case loadBalancingPolicy = "loadBalancingPolicy"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.selector = try container.decode(Swift.String.self, forKey: .selector)
    self.address = try container.decode(Swift.String.self, forKey: .address)
    self.deadline = try container.decode(Swift.Double.self, forKey: .deadline)
    self.minDeadline = try container.decode(Swift.Double.self, forKey: .minDeadline)
    self.operationDeadline = try container.decode(Swift.Double.self, forKey: .operationDeadline)
    self.pathTranslation = try container.decode(
      BackendRule.PathTranslation.self, forKey: .pathTranslation)
    self.`protocol` = try container.decode(Swift.String.self, forKey: .`protocol`)
    self.overridesByRequestProtocol = try container.decode(
      [Swift.String: BackendRule].self, forKey: .overridesByRequestProtocol)
    self.loadBalancingPolicy = try container.decode(Swift.String.self, forKey: .loadBalancingPolicy)

    var authentication: OneOf_Authentication? = nil
    let authenticationCheckAndSet = {
      if authentication != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'authentication'"))
      }
      authentication = $0
    }
    if let jwtAudience = try container.decodeIfPresent(Swift.String.self, forKey: .jwtAudience) {
      try authenticationCheckAndSet(.jwtAudience(jwtAudience))
    }
    if let disableAuth = try container.decodeIfPresent(Swift.Bool.self, forKey: .disableAuth) {
      try authenticationCheckAndSet(.disableAuth(disableAuth))
    }
    self.authentication = authentication
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.selector, forKey: .selector)
    try container.encode(self.address, forKey: .address)
    try container.encode(self.deadline, forKey: .deadline)
    try container.encode(self.minDeadline, forKey: .minDeadline)
    try container.encode(self.operationDeadline, forKey: .operationDeadline)
    try container.encode(self.pathTranslation, forKey: .pathTranslation)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    try container.encode(self.overridesByRequestProtocol, forKey: .overridesByRequestProtocol)
    try container.encode(self.loadBalancingPolicy, forKey: .loadBalancingPolicy)

    if let choice = self.authentication {
      switch choice {
      case .jwtAudience(let value):
        try container.encode(value, forKey: .jwtAudience)
      case .disableAuth(let value):
        try container.encode(value, forKey: .disableAuth)
      }
    }
  }

  /// Path Translation specifies how to combine the backend address with the
  /// request path in order to produce the appropriate forwarding URL for the
  /// request.
  ///
  /// Path Translation is applicable only to HTTP-based backends. Backends which
  /// do not accept requests over HTTP/HTTPS should leave `path_translation`
  /// unspecified.
  public enum PathTranslation: Codable, Equatable, Sendable {
    case unspecified
    case constantAddress
    case appendPathToAddress
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .constantAddress: return 1
      case .appendPathToAddress: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "PATH_TRANSLATION_UNSPECIFIED"
      case .constantAddress: return "CONSTANT_ADDRESS"
      case .appendPathToAddress: return "APPEND_PATH_TO_ADDRESS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "PATH_TRANSLATION_UNSPECIFIED": self = .unspecified
      case "CONSTANT_ADDRESS": self = .constantAddress
      case "APPEND_PATH_TO_ADDRESS": self = .appendPathToAddress
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .constantAddress
      case 2: self = .appendPathToAddress
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .constantAddress: return try container.encode(1)
      case .appendPathToAddress: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Authentication settings used by the backend.
  ///
  /// These are typically used to provide service management functionality to
  /// a backend served on a publicly-routable URL. The `authentication`
  /// details should match the authentication behavior used by the backend.
  ///
  /// For example, specifying `jwt_audience` implies that the backend expects
  /// authentication via a JWT.
  ///
  /// When authentication is unspecified, the resulting behavior is the same
  /// as `disable_auth` set to `true`.
  ///
  /// Refer to https://developers.google.com/identity/protocols/OpenIDConnect for
  /// JWT ID token.
  public enum OneOf_Authentication: Codable, Equatable, Sendable {
    /// The JWT audience is used when generating a JWT ID token for the backend.
    /// This ID token will be added in the HTTP "authorization" header, and sent
    /// to the backend.
    case jwtAudience(Swift.String)
    /// When disable_auth is true, a JWT ID token won't be generated and the
    /// original "Authorization" HTTP header will be preserved. If the header is
    /// used to carry the original token and is expected by the backend, this
    /// field must be set to true to preserve the header.
    case disableAuth(Swift.Bool)
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.api.BackendRule" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
