// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// `BatchingSettingsProto` specifies a set of batching thresholds, each of
/// which acts as a trigger to send a batch of messages as a request. At least
/// one threshold must be positive nonzero.
public struct BatchingSettingsProto: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The number of elements of a field collected into a batch which, if
  /// exceeded, causes the batch to be sent.
  public var elementCountThreshold: Swift.Int32 = Swift.Int32()

  /// The aggregated size of the batched field which, if exceeded, causes the
  /// batch to be sent. This size is computed by aggregating the sizes of the
  /// request field to be batched, not of the entire request message.
  public var requestByteThreshold: Swift.Int64 = Swift.Int64()

  /// The duration after which a batch should be sent, starting from the addition
  /// of the first message to that batch.
  public var delayThreshold: GoogleCloudWKT.Duration? = nil

  /// The maximum number of elements collected in a batch that could be accepted
  /// by server.
  public var elementCountLimit: Swift.Int32 = Swift.Int32()

  /// The maximum size of the request that could be accepted by server.
  public var requestByteLimit: Swift.Int32 = Swift.Int32()

  /// The maximum number of elements allowed by flow control.
  public var flowControlElementLimit: Swift.Int32 = Swift.Int32()

  /// The maximum size of data allowed by flow control.
  public var flowControlByteLimit: Swift.Int32 = Swift.Int32()

  /// The behavior to take when the flow control limit is exceeded.
  public var flowControlLimitExceededBehavior: FlowControlLimitExceededBehaviorProto =
    FlowControlLimitExceededBehaviorProto()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `BatchingSettingsProto`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchingSettingsProto().with { $0.elementCountThreshold = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let elementCountThreshold = CodingKeys(stringValue: "elementCountThreshold")
    static let requestByteThreshold = CodingKeys(stringValue: "requestByteThreshold")
    static let delayThreshold = CodingKeys(stringValue: "delayThreshold")
    static let elementCountLimit = CodingKeys(stringValue: "elementCountLimit")
    static let requestByteLimit = CodingKeys(stringValue: "requestByteLimit")
    static let flowControlElementLimit = CodingKeys(stringValue: "flowControlElementLimit")
    static let flowControlByteLimit = CodingKeys(stringValue: "flowControlByteLimit")
    static let flowControlLimitExceededBehavior = CodingKeys(
      stringValue: "flowControlLimitExceededBehavior")

    static let _knownKeys: Set<Swift.String> = [
      "elementCountThreshold",
      "requestByteThreshold",
      "delayThreshold",
      "elementCountLimit",
      "requestByteLimit",
      "flowControlElementLimit",
      "flowControlByteLimit",
      "flowControlLimitExceededBehavior",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .elementCountThreshold) {
      self.elementCountThreshold = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .requestByteThreshold) {
      self.requestByteThreshold = value
    }
    self.delayThreshold = try container.decodeIfPresent(
      GoogleCloudWKT.Duration.self, forKey: .delayThreshold)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .elementCountLimit) {
      self.elementCountLimit = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .requestByteLimit) {
      self.requestByteLimit = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .flowControlElementLimit)
    {
      self.flowControlElementLimit = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .flowControlByteLimit) {
      self.flowControlByteLimit = value
    }
    if let value = try container.decodeIfPresent(
      FlowControlLimitExceededBehaviorProto.self, forKey: .flowControlLimitExceededBehavior)
    {
      self.flowControlLimitExceededBehavior = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.elementCountThreshold, forKey: .elementCountThreshold)
    try container.encode(self.requestByteThreshold, forKey: .requestByteThreshold)
    try container.encodeIfPresent(self.delayThreshold, forKey: .delayThreshold)
    try container.encode(self.elementCountLimit, forKey: .elementCountLimit)
    try container.encode(self.requestByteLimit, forKey: .requestByteLimit)
    try container.encode(self.flowControlElementLimit, forKey: .flowControlElementLimit)
    try container.encode(self.flowControlByteLimit, forKey: .flowControlByteLimit)
    try container.encode(
      self.flowControlLimitExceededBehavior, forKey: .flowControlLimitExceededBehavior)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.BatchingSettingsProto"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
