// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// `BatchingSettingsProto` specifies a set of batching thresholds, each of
/// which acts as a trigger to send a batch of messages as a request. At least
/// one threshold must be positive nonzero.
public struct BatchingSettingsProto: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The number of elements of a field collected into a batch which, if
  /// exceeded, causes the batch to be sent.
  public var elementCountThreshold: Swift.Int32 = Swift.Int32()

  /// The aggregated size of the batched field which, if exceeded, causes the
  /// batch to be sent. This size is computed by aggregating the sizes of the
  /// request field to be batched, not of the entire request message.
  public var requestByteThreshold: Swift.Int64 = Swift.Int64()

  /// The duration after which a batch should be sent, starting from the addition
  /// of the first message to that batch.
  public var delayThreshold: GoogleCloudWkt.Duration? = nil

  /// The maximum number of elements collected in a batch that could be accepted
  /// by server.
  public var elementCountLimit: Swift.Int32 = Swift.Int32()

  /// The maximum size of the request that could be accepted by server.
  public var requestByteLimit: Swift.Int32 = Swift.Int32()

  /// The maximum number of elements allowed by flow control.
  public var flowControlElementLimit: Swift.Int32 = Swift.Int32()

  /// The maximum size of data allowed by flow control.
  public var flowControlByteLimit: Swift.Int32 = Swift.Int32()

  /// The behavior to take when the flow control limit is exceeded.
  public var flowControlLimitExceededBehavior: FlowControlLimitExceededBehaviorProto =
    FlowControlLimitExceededBehaviorProto()

  /// Initialize a new instance of `BatchingSettingsProto`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchingSettingsProto().with { $0.elementCountThreshold = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.BatchingSettingsProto"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
