// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// `BatchingDescriptorProto` specifies the fields of the request message to be
/// used for batching, and, optionally, the fields of the response message to be
/// used for demultiplexing.
public struct BatchingDescriptorProto: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The repeated field in the request message to be aggregated by batching.
  public var batchedField: Swift.String = Swift.String()

  /// A list of the fields in the request message. Two requests will be batched
  /// together only if the values of every field specified in
  /// `request_discriminator_fields` is equal between the two requests.
  public var discriminatorFields: [Swift.String] = []

  /// Optional. When present, indicates the field in the response message to be
  /// used to demultiplex the response into multiple response messages, in
  /// correspondence with the multiple request messages originally batched
  /// together.
  public var subresponseField: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BatchingDescriptorProto`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchingDescriptorProto().with { $0.batchedField = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let batchedField = CodingKeys(stringValue: "batchedField")
    static let discriminatorFields = CodingKeys(stringValue: "discriminatorFields")
    static let subresponseField = CodingKeys(stringValue: "subresponseField")

    static let _knownKeys: Set<Swift.String> = [
      "batchedField",
      "discriminatorFields",
      "subresponseField",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .batchedField) {
      self.batchedField = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .discriminatorFields)
    {
      self.discriminatorFields = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subresponseField) {
      self.subresponseField = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.batchedField, forKey: .batchedField)
    try container.encode(self.discriminatorFields, forKey: .discriminatorFields)
    try container.encode(self.subresponseField, forKey: .subresponseField)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.BatchingDescriptorProto"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
