// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The organization for which the client libraries are being published.
/// Affects the url where generated docs are published, etc.
public enum ClientLibraryOrganization: Codable, Equatable, Sendable {
  /// Not useful.
  case unspecified
  /// Google Cloud Platform Org.
  case cloud
  /// Ads (Advertising) Org.
  case ads
  /// Photos Org.
  case photos
  /// Street View Org.
  case streetView
  /// Shopping Org.
  case shopping
  /// Geo Org.
  case geo
  /// Generative AI - https://developers.generativeai.google
  case generativeAi
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .cloud: return 1
    case .ads: return 2
    case .photos: return 3
    case .streetView: return 4
    case .shopping: return 5
    case .geo: return 6
    case .generativeAi: return 7
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "CLIENT_LIBRARY_ORGANIZATION_UNSPECIFIED"
    case .cloud: return "CLOUD"
    case .ads: return "ADS"
    case .photos: return "PHOTOS"
    case .streetView: return "STREET_VIEW"
    case .shopping: return "SHOPPING"
    case .geo: return "GEO"
    case .generativeAi: return "GENERATIVE_AI"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "CLIENT_LIBRARY_ORGANIZATION_UNSPECIFIED": self = .unspecified
    case "CLOUD": self = .cloud
    case "ADS": self = .ads
    case "PHOTOS": self = .photos
    case "STREET_VIEW": self = .streetView
    case "SHOPPING": self = .shopping
    case "GEO": self = .geo
    case "GENERATIVE_AI": self = .generativeAi
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .cloud
    case 2: self = .ads
    case 3: self = .photos
    case 4: self = .streetView
    case 5: self = .shopping
    case 6: self = .geo
    case 7: self = .generativeAi
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .cloud: return try container.encode(1)
    case .ads: return try container.encode(2)
    case .photos: return try container.encode(3)
    case .streetView: return try container.encode(4)
    case .shopping: return try container.encode(5)
    case .geo: return try container.encode(6)
    case .generativeAi: return try container.encode(7)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
