// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Details about how and where to publish client libraries.
public struct ClientLibrarySettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Version of the API to apply these settings to. This is the full protobuf
  /// package for the API, ending in the version element.
  /// Examples: "google.cloud.speech.v1" and "google.spanner.admin.database.v1".
  public var version: Swift.String = Swift.String()

  /// Launch stage of this version of the API.
  public var launchStage: LaunchStage = LaunchStage()

  /// When using transport=rest, the client request will encode enums as
  /// numbers rather than strings.
  public var restNumericEnums: Swift.Bool = Swift.Bool()

  /// Settings for legacy Java features, supported in the Service YAML.
  public var javaSettings: JavaSettings? = nil

  /// Settings for C++ client libraries.
  public var cppSettings: CppSettings? = nil

  /// Settings for PHP client libraries.
  public var phpSettings: PhpSettings? = nil

  /// Settings for Python client libraries.
  public var pythonSettings: PythonSettings? = nil

  /// Settings for Node client libraries.
  public var nodeSettings: NodeSettings? = nil

  /// Settings for .NET client libraries.
  public var dotnetSettings: DotnetSettings? = nil

  /// Settings for Ruby client libraries.
  public var rubySettings: RubySettings? = nil

  /// Settings for Go client libraries.
  public var goSettings: GoSettings? = nil

  /// Initialize a new instance of `ClientLibrarySettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClientLibrarySettings().with { $0.version = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.ClientLibrarySettings"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
