// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Details about how and where to publish client libraries.
public struct ClientLibrarySettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Version of the API to apply these settings to. This is the full protobuf
  /// package for the API, ending in the version element.
  /// Examples: "google.cloud.speech.v1" and "google.spanner.admin.database.v1".
  public var version: Swift.String = Swift.String()

  /// Launch stage of this version of the API.
  public var launchStage: LaunchStage = LaunchStage()

  /// When using transport=rest, the client request will encode enums as
  /// numbers rather than strings.
  public var restNumericEnums: Swift.Bool = Swift.Bool()

  /// Settings for legacy Java features, supported in the Service YAML.
  public var javaSettings: JavaSettings? = nil

  /// Settings for C++ client libraries.
  public var cppSettings: CppSettings? = nil

  /// Settings for PHP client libraries.
  public var phpSettings: PhpSettings? = nil

  /// Settings for Python client libraries.
  public var pythonSettings: PythonSettings? = nil

  /// Settings for Node client libraries.
  public var nodeSettings: NodeSettings? = nil

  /// Settings for .NET client libraries.
  public var dotnetSettings: DotnetSettings? = nil

  /// Settings for Ruby client libraries.
  public var rubySettings: RubySettings? = nil

  /// Settings for Go client libraries.
  public var goSettings: GoSettings? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ClientLibrarySettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClientLibrarySettings().with { $0.version = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let version = CodingKeys(stringValue: "version")
    static let launchStage = CodingKeys(stringValue: "launchStage")
    static let restNumericEnums = CodingKeys(stringValue: "restNumericEnums")
    static let javaSettings = CodingKeys(stringValue: "javaSettings")
    static let cppSettings = CodingKeys(stringValue: "cppSettings")
    static let phpSettings = CodingKeys(stringValue: "phpSettings")
    static let pythonSettings = CodingKeys(stringValue: "pythonSettings")
    static let nodeSettings = CodingKeys(stringValue: "nodeSettings")
    static let dotnetSettings = CodingKeys(stringValue: "dotnetSettings")
    static let rubySettings = CodingKeys(stringValue: "rubySettings")
    static let goSettings = CodingKeys(stringValue: "goSettings")

    static let _knownKeys: Set<Swift.String> = [
      "version",
      "launchStage",
      "restNumericEnums",
      "javaSettings",
      "cppSettings",
      "phpSettings",
      "pythonSettings",
      "nodeSettings",
      "dotnetSettings",
      "rubySettings",
      "goSettings",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    if let value = try container.decodeIfPresent(LaunchStage.self, forKey: .launchStage) {
      self.launchStage = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .restNumericEnums) {
      self.restNumericEnums = value
    }
    self.javaSettings = try container.decodeIfPresent(JavaSettings.self, forKey: .javaSettings)
    self.cppSettings = try container.decodeIfPresent(CppSettings.self, forKey: .cppSettings)
    self.phpSettings = try container.decodeIfPresent(PhpSettings.self, forKey: .phpSettings)
    self.pythonSettings = try container.decodeIfPresent(
      PythonSettings.self, forKey: .pythonSettings)
    self.nodeSettings = try container.decodeIfPresent(NodeSettings.self, forKey: .nodeSettings)
    self.dotnetSettings = try container.decodeIfPresent(
      DotnetSettings.self, forKey: .dotnetSettings)
    self.rubySettings = try container.decodeIfPresent(RubySettings.self, forKey: .rubySettings)
    self.goSettings = try container.decodeIfPresent(GoSettings.self, forKey: .goSettings)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.version, forKey: .version)
    try container.encode(self.launchStage, forKey: .launchStage)
    try container.encode(self.restNumericEnums, forKey: .restNumericEnums)
    try container.encodeIfPresent(self.javaSettings, forKey: .javaSettings)
    try container.encodeIfPresent(self.cppSettings, forKey: .cppSettings)
    try container.encodeIfPresent(self.phpSettings, forKey: .phpSettings)
    try container.encodeIfPresent(self.pythonSettings, forKey: .pythonSettings)
    try container.encodeIfPresent(self.nodeSettings, forKey: .nodeSettings)
    try container.encodeIfPresent(self.dotnetSettings, forKey: .dotnetSettings)
    try container.encodeIfPresent(self.rubySettings, forKey: .rubySettings)
    try container.encodeIfPresent(self.goSettings, forKey: .goSettings)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.ClientLibrarySettings"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
