// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Output generated from semantically comparing two versions of a service
/// configuration.
///
/// Includes detailed information about a field that have changed with
/// applicable advice about potential consequences for the change, such as
/// backwards-incompatibility.
public struct ConfigChange: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Object hierarchy path to the change, with levels separated by a '.'
  /// character. For repeated fields, an applicable unique identifier field is
  /// used for the index (usually selector, name, or id). For maps, the term
  /// 'key' is used. If the field has no unique identifier, the numeric index
  /// is used.
  /// Examples:
  /// - visibility.rules[selector=="google.LibraryService.ListBooks"].restriction
  /// - quota.metric_rules[selector=="google"].metric_costs[key=="reads"].value
  /// - logging.producer_destinations[0]
  public var element: Swift.String = Swift.String()

  /// Value of the changed object in the old Service configuration,
  /// in JSON format. This field will not be populated if ChangeType == ADDED.
  public var oldValue: Swift.String = Swift.String()

  /// Value of the changed object in the new Service configuration,
  /// in JSON format. This field will not be populated if ChangeType == REMOVED.
  public var newValue: Swift.String = Swift.String()

  /// The type for this change, either ADDED, REMOVED, or MODIFIED.
  public var changeType: ChangeType = ChangeType()

  /// Collection of advice provided for this change, useful for determining the
  /// possible impact of this change.
  public var advices: [Advice] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ConfigChange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConfigChange().with { $0.element = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let element = CodingKeys(stringValue: "element")
    static let oldValue = CodingKeys(stringValue: "oldValue")
    static let newValue = CodingKeys(stringValue: "newValue")
    static let changeType = CodingKeys(stringValue: "changeType")
    static let advices = CodingKeys(stringValue: "advices")

    static let _knownKeys: Set<Swift.String> = [
      "element",
      "oldValue",
      "newValue",
      "changeType",
      "advices",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .element) {
      self.element = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .oldValue) {
      self.oldValue = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .newValue) {
      self.newValue = value
    }
    if let value = try container.decodeIfPresent(ChangeType.self, forKey: .changeType) {
      self.changeType = value
    }
    if let value = try container.decodeIfPresent([Advice].self, forKey: .advices) {
      self.advices = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.element, forKey: .element)
    try container.encode(self.oldValue, forKey: .oldValue)
    try container.encode(self.newValue, forKey: .newValue)
    try container.encode(self.changeType, forKey: .changeType)
    try container.encode(self.advices, forKey: .advices)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.ConfigChange"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
