// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Output generated from semantically comparing two versions of a service
/// configuration.
///
/// Includes detailed information about a field that have changed with
/// applicable advice about potential consequences for the change, such as
/// backwards-incompatibility.
public struct ConfigChange: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Object hierarchy path to the change, with levels separated by a '.'
  /// character. For repeated fields, an applicable unique identifier field is
  /// used for the index (usually selector, name, or id). For maps, the term
  /// 'key' is used. If the field has no unique identifier, the numeric index
  /// is used.
  /// Examples:
  /// - visibility.rules[selector=="google.LibraryService.ListBooks"].restriction
  /// - quota.metric_rules[selector=="google"].metric_costs[key=="reads"].value
  /// - logging.producer_destinations[0]
  public var element: Swift.String

  /// Value of the changed object in the old Service configuration,
  /// in JSON format. This field will not be populated if ChangeType == ADDED.
  public var oldValue: Swift.String

  /// Value of the changed object in the new Service configuration,
  /// in JSON format. This field will not be populated if ChangeType == REMOVED.
  public var newValue: Swift.String

  /// The type for this change, either ADDED, REMOVED, or MODIFIED.
  public var changeType: ChangeType

  /// Collection of advice provided for this change, useful for determining the
  /// possible impact of this change.
  public var advices: [Advice]

  /// Initialize a new instance of `ConfigChange`.
  public init(
    element: Swift.String = Swift.String(),
    oldValue: Swift.String = Swift.String(),
    newValue: Swift.String = Swift.String(),
    changeType: ChangeType = ChangeType(),
    advices: [Advice] = [],
  ) {
    self.element = element
    self.oldValue = oldValue
    self.newValue = newValue
    self.changeType = changeType
    self.advices = advices
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.api.ConfigChange" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
