// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A context rule provides information about the context for an individual API
/// element.
public struct ContextRule: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Selects the methods to which this rule applies.
  ///
  /// Refer to [selector][google.api.DocumentationRule.selector] for syntax
  /// details.
  ///
  /// [google.api.DocumentationRule.selector]: <doc:DocumentationRule/selector>
  public var selector: Swift.String = Swift.String()

  /// A list of full type names of requested contexts, only the requested context
  /// will be made available to the backend.
  public var requested: [Swift.String] = []

  /// A list of full type names of provided contexts. It is used to support
  /// propagating HTTP headers and ETags from the response extension.
  public var provided: [Swift.String] = []

  /// A list of full type names or extension IDs of extensions allowed in grpc
  /// side channel from client to backend.
  public var allowedRequestExtensions: [Swift.String] = []

  /// A list of full type names or extension IDs of extensions allowed in grpc
  /// side channel from backend to client.
  public var allowedResponseExtensions: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ContextRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ContextRule().with { $0.selector = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let selector = CodingKeys(stringValue: "selector")
    static let requested = CodingKeys(stringValue: "requested")
    static let provided = CodingKeys(stringValue: "provided")
    static let allowedRequestExtensions = CodingKeys(stringValue: "allowedRequestExtensions")
    static let allowedResponseExtensions = CodingKeys(stringValue: "allowedResponseExtensions")

    static let _knownKeys: Set<Swift.String> = [
      "selector",
      "requested",
      "provided",
      "allowedRequestExtensions",
      "allowedResponseExtensions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .selector) {
      self.selector = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .requested) {
      self.requested = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .provided) {
      self.provided = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .allowedRequestExtensions)
    {
      self.allowedRequestExtensions = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .allowedResponseExtensions)
    {
      self.allowedResponseExtensions = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.selector, forKey: .selector)
    try container.encode(self.requested, forKey: .requested)
    try container.encode(self.provided, forKey: .provided)
    try container.encode(self.allowedRequestExtensions, forKey: .allowedRequestExtensions)
    try container.encode(self.allowedResponseExtensions, forKey: .allowedResponseExtensions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.ContextRule"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
