// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Selects and configures the service controller used by the service.
///
/// Example:
///
///     control:
///       environment: servicecontrol.googleapis.com
public struct Control: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The service controller environment to use. If empty, no control plane
  /// feature (like quota and billing) will be enabled. The recommended value for
  /// most services is servicecontrol.googleapis.com
  public var environment: Swift.String

  /// Defines policies applying to the API methods of the service.
  public var methodPolicies: [MethodPolicy]

  /// Initialize a new instance of `Control`.
  public init(
    environment: Swift.String = Swift.String(),
    methodPolicies: [MethodPolicy] = [],
  ) {
    self.environment = environment
    self.methodPolicies = methodPolicies
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.api.Control" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
