// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A context rule provides information about the context for an individual API
/// element.
public struct ContextRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Selects the methods to which this rule applies.
  ///
  /// Refer to [selector][google.api.DocumentationRule.selector] for syntax
  /// details.
  ///
  /// [google.api.DocumentationRule.selector]: <doc:DocumentationRule/selector>
  public var selector: Swift.String

  /// A list of full type names of requested contexts, only the requested context
  /// will be made available to the backend.
  public var requested: [Swift.String]

  /// A list of full type names of provided contexts. It is used to support
  /// propagating HTTP headers and ETags from the response extension.
  public var provided: [Swift.String]

  /// A list of full type names or extension IDs of extensions allowed in grpc
  /// side channel from client to backend.
  public var allowedRequestExtensions: [Swift.String]

  /// A list of full type names or extension IDs of extensions allowed in grpc
  /// side channel from backend to client.
  public var allowedResponseExtensions: [Swift.String]

  /// Initialize a new instance of `ContextRule`.
  public init(
    selector: Swift.String = Swift.String(),
    requested: [Swift.String] = [],
    provided: [Swift.String] = [],
    allowedRequestExtensions: [Swift.String] = [],
    allowedResponseExtensions: [Swift.String] = [],
  ) {
    self.selector = selector
    self.requested = requested
    self.provided = provided
    self.allowedRequestExtensions = allowedRequestExtensions
    self.allowedResponseExtensions = allowedResponseExtensions
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.api.ContextRule" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
