// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// `Distribution` contains summary statistics for a population of values. It
/// optionally contains a histogram representing the distribution of those values
/// across a set of buckets.
///
/// The summary statistics are the count, mean, sum of the squared deviation from
/// the mean, the minimum, and the maximum of the set of population of values.
/// The histogram is based on a sequence of buckets and gives a count of values
/// that fall into each bucket. The boundaries of the buckets are given either
/// explicitly or by formulas for buckets of fixed or exponentially increasing
/// widths.
///
/// Although it is not forbidden, it is generally a bad idea to include
/// non-finite values (infinities or NaNs) in the population of values, as this
/// will render the `mean` and `sum_of_squared_deviation` fields meaningless.
public struct Distribution: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The number of values in the population. Must be non-negative. This value
  /// must equal the sum of the values in `bucket_counts` if a histogram is
  /// provided.
  public var count: Swift.Int64

  /// The arithmetic mean of the values in the population. If `count` is zero
  /// then this field must be zero.
  public var mean: Swift.Double

  /// The sum of squared deviations from the mean of the values in the
  /// population. For values x_i this is:
  ///
  ///     Sum[i=1..n]((x_i - mean)^2)
  ///
  /// Knuth, "The Art of Computer Programming", Vol. 2, page 232, 3rd edition
  /// describes Welford's method for accumulating this sum in one pass.
  ///
  /// If `count` is zero then this field must be zero.
  public var sumOfSquaredDeviation: Swift.Double

  /// If specified, contains the range of the population values. The field
  /// must not be present if the `count` is zero.
  public var range: Distribution.Range?

  /// Defines the histogram bucket boundaries. If the distribution does not
  /// contain a histogram, then omit this field.
  public var bucketOptions: Distribution.BucketOptions?

  /// The number of values in each bucket of the histogram, as described in
  /// `bucket_options`. If the distribution does not have a histogram, then omit
  /// this field. If there is a histogram, then the sum of the values in
  /// `bucket_counts` must equal the value in the `count` field of the
  /// distribution.
  ///
  /// If present, `bucket_counts` should contain N values, where N is the number
  /// of buckets specified in `bucket_options`. If you supply fewer than N
  /// values, the remaining values are assumed to be 0.
  ///
  /// The order of the values in `bucket_counts` follows the bucket numbering
  /// schemes described for the three bucket types. The first value must be the
  /// count for the underflow bucket (number 0). The next N-2 values are the
  /// counts for the finite buckets (number 1 through N-2). The N'th value in
  /// `bucket_counts` is the count for the overflow bucket (number N-1).
  public var bucketCounts: [Swift.Int64]

  /// Must be in increasing order of `value` field.
  public var exemplars: [Distribution.Exemplar]

  /// Initialize a new instance of `Distribution`.
  public init(
    count: Swift.Int64 = Swift.Int64(),
    mean: Swift.Double = Swift.Double(),
    sumOfSquaredDeviation: Swift.Double = Swift.Double(),
    range: Distribution.Range? = nil,
    bucketOptions: Distribution.BucketOptions? = nil,
    bucketCounts: [Swift.Int64] = [],
    exemplars: [Distribution.Exemplar] = [],
  ) {
    self.count = count
    self.mean = mean
    self.sumOfSquaredDeviation = sumOfSquaredDeviation
    self.range = range
    self.bucketOptions = bucketOptions
    self.bucketCounts = bucketCounts
    self.exemplars = exemplars
  }

  /// The range of the population values.
  public struct Range: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The minimum of the population values.
    public var min: Swift.Double

    /// The maximum of the population values.
    public var max: Swift.Double

    /// Initialize a new instance of `Range`.
    public init(
      min: Swift.Double = Swift.Double(),
      max: Swift.Double = Swift.Double(),
    ) {
      self.min = min
      self.max = max
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.api.Distribution.Range"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// `BucketOptions` describes the bucket boundaries used to create a histogram
  /// for the distribution. The buckets can be in a linear sequence, an
  /// exponential sequence, or each bucket can be specified explicitly.
  /// `BucketOptions` does not include the number of values in each bucket.
  ///
  /// A bucket has an inclusive lower bound and exclusive upper bound for the
  /// values that are counted for that bucket. The upper bound of a bucket must
  /// be strictly greater than the lower bound. The sequence of N buckets for a
  /// distribution consists of an underflow bucket (number 0), zero or more
  /// finite buckets (number 1 through N - 2) and an overflow bucket (number N -
  /// 1). The buckets are contiguous: the lower bound of bucket i (i > 0) is the
  /// same as the upper bound of bucket i - 1. The buckets span the whole range
  /// of finite values: lower bound of the underflow bucket is -infinity and the
  /// upper bound of the overflow bucket is +infinity. The finite buckets are
  /// so-called because both bounds are finite.
  public struct BucketOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Exactly one of these three fields must be set.
    public var options: OneOf_Options?

    /// Initialize a new instance of `BucketOptions`.
    public init(
      options: OneOf_Options? = nil,
    ) {
      self.options = options
    }

    private enum CodingKeys: String, CodingKey {
      case linearBuckets = "linearBuckets"
      case exponentialBuckets = "exponentialBuckets"
      case explicitBuckets = "explicitBuckets"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var options: OneOf_Options? = nil
      let optionsCheckAndSet = { (value: OneOf_Options) throws in
        if options != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'options'"))
        }
        options = value
      }
      if let linearBuckets = try container.decodeIfPresent(
        Distribution.BucketOptions.Linear?.self, forKey: .linearBuckets)
      {
        try optionsCheckAndSet(.linearBuckets(linearBuckets))
      }
      if let exponentialBuckets = try container.decodeIfPresent(
        Distribution.BucketOptions.Exponential?.self, forKey: .exponentialBuckets)
      {
        try optionsCheckAndSet(.exponentialBuckets(exponentialBuckets))
      }
      if let explicitBuckets = try container.decodeIfPresent(
        Distribution.BucketOptions.Explicit?.self, forKey: .explicitBuckets)
      {
        try optionsCheckAndSet(.explicitBuckets(explicitBuckets))
      }
      self.options = options
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.options {
        switch choice {
        case .linearBuckets(let value):
          try container.encode(value, forKey: .linearBuckets)
        case .exponentialBuckets(let value):
          try container.encode(value, forKey: .exponentialBuckets)
        case .explicitBuckets(let value):
          try container.encode(value, forKey: .explicitBuckets)
        }
      }
    }

    /// Specifies a linear sequence of buckets that all have the same width
    /// (except overflow and underflow). Each bucket represents a constant
    /// absolute uncertainty on the specific value in the bucket.
    ///
    /// There are `num_finite_buckets + 2` (= N) buckets. Bucket `i` has the
    /// following boundaries:
    ///
    ///    Upper bound (0 <= i < N-1):     offset + (width * i).
    ///
    ///    Lower bound (1 <= i < N):       offset + (width * (i - 1)).
    public struct Linear: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Must be greater than 0.
      public var numFiniteBuckets: Swift.Int32

      /// Must be greater than 0.
      public var width: Swift.Double

      /// Lower bound of the first bucket.
      public var offset: Swift.Double

      /// Initialize a new instance of `Linear`.
      public init(
        numFiniteBuckets: Swift.Int32 = Swift.Int32(),
        width: Swift.Double = Swift.Double(),
        offset: Swift.Double = Swift.Double(),
      ) {
        self.numFiniteBuckets = numFiniteBuckets
        self.width = width
        self.offset = offset
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.api.Distribution.BucketOptions.Linear"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Specifies an exponential sequence of buckets that have a width that is
    /// proportional to the value of the lower bound. Each bucket represents a
    /// constant relative uncertainty on a specific value in the bucket.
    ///
    /// There are `num_finite_buckets + 2` (= N) buckets. Bucket `i` has the
    /// following boundaries:
    ///
    ///    Upper bound (0 <= i < N-1):     scale * (growth_factor ^ i).
    ///
    ///    Lower bound (1 <= i < N):       scale * (growth_factor ^ (i - 1)).
    public struct Exponential: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Must be greater than 0.
      public var numFiniteBuckets: Swift.Int32

      /// Must be greater than 1.
      public var growthFactor: Swift.Double

      /// Must be greater than 0.
      public var scale: Swift.Double

      /// Initialize a new instance of `Exponential`.
      public init(
        numFiniteBuckets: Swift.Int32 = Swift.Int32(),
        growthFactor: Swift.Double = Swift.Double(),
        scale: Swift.Double = Swift.Double(),
      ) {
        self.numFiniteBuckets = numFiniteBuckets
        self.growthFactor = growthFactor
        self.scale = scale
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.api.Distribution.BucketOptions.Exponential"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Specifies a set of buckets with arbitrary widths.
    ///
    /// There are `size(bounds) + 1` (= N) buckets. Bucket `i` has the following
    /// boundaries:
    ///
    ///    Upper bound (0 <= i < N-1):     bounds[i]
    ///    Lower bound (1 <= i < N);       bounds[i - 1]
    ///
    /// The `bounds` field must contain at least one element. If `bounds` has
    /// only one element, then there are no finite buckets, and that single
    /// element is the common boundary of the overflow and underflow buckets.
    public struct Explicit: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The values must be monotonically increasing.
      public var bounds: [Swift.Double]

      /// Initialize a new instance of `Explicit`.
      public init(
        bounds: [Swift.Double] = [],
      ) {
        self.bounds = bounds
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.api.Distribution.BucketOptions.Explicit"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Exactly one of these three fields must be set.
    public enum OneOf_Options: Codable, Equatable, Sendable {
      /// The linear bucket.
      indirect case linearBuckets(Distribution.BucketOptions.Linear?)
      /// The exponential buckets.
      indirect case exponentialBuckets(Distribution.BucketOptions.Exponential?)
      /// The explicit buckets.
      indirect case explicitBuckets(Distribution.BucketOptions.Explicit?)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.api.Distribution.BucketOptions"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Exemplars are example points that may be used to annotate aggregated
  /// distribution values. They are metadata that gives information about a
  /// particular value added to a Distribution bucket, such as a trace ID that
  /// was active when a value was added. They may contain further information,
  /// such as a example values and timestamps, origin, etc.
  public struct Exemplar: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Value of the exemplar point. This value determines to which bucket the
    /// exemplar belongs.
    public var value: Swift.Double

    /// The observation (sampling) time of the above value.
    public var timestamp: GoogleCloudWkt.Timestamp?

    /// Contextual information about the example value. Examples are:
    ///
    ///   Trace: type.googleapis.com/google.monitoring.v3.SpanContext
    ///
    ///   Literal string: type.googleapis.com/google.protobuf.StringValue
    ///
    ///   Labels dropped during aggregation:
    ///     type.googleapis.com/google.monitoring.v3.DroppedLabels
    ///
    /// There may be only a single attachment of any given message type in a
    /// single exemplar, and this is enforced by the system.
    public var attachments: [GoogleCloudWkt.`Any`]

    /// Initialize a new instance of `Exemplar`.
    public init(
      value: Swift.Double = Swift.Double(),
      timestamp: GoogleCloudWkt.Timestamp? = nil,
      attachments: [GoogleCloudWkt.`Any`] = [],
    ) {
      self.value = value
      self.timestamp = timestamp
      self.attachments = attachments
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.api.Distribution.Exemplar"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.api.Distribution" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
