// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// `Distribution` contains summary statistics for a population of values. It
/// optionally contains a histogram representing the distribution of those values
/// across a set of buckets.
///
/// The summary statistics are the count, mean, sum of the squared deviation from
/// the mean, the minimum, and the maximum of the set of population of values.
/// The histogram is based on a sequence of buckets and gives a count of values
/// that fall into each bucket. The boundaries of the buckets are given either
/// explicitly or by formulas for buckets of fixed or exponentially increasing
/// widths.
///
/// Although it is not forbidden, it is generally a bad idea to include
/// non-finite values (infinities or NaNs) in the population of values, as this
/// will render the `mean` and `sum_of_squared_deviation` fields meaningless.
public struct Distribution: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The number of values in the population. Must be non-negative. This value
  /// must equal the sum of the values in `bucket_counts` if a histogram is
  /// provided.
  public var count: Swift.Int64 = Swift.Int64()

  /// The arithmetic mean of the values in the population. If `count` is zero
  /// then this field must be zero.
  public var mean: Swift.Double = Swift.Double()

  /// The sum of squared deviations from the mean of the values in the
  /// population. For values x_i this is:
  ///
  ///     Sum[i=1..n]((x_i - mean)^2)
  ///
  /// Knuth, "The Art of Computer Programming", Vol. 2, page 232, 3rd edition
  /// describes Welford's method for accumulating this sum in one pass.
  ///
  /// If `count` is zero then this field must be zero.
  public var sumOfSquaredDeviation: Swift.Double = Swift.Double()

  /// If specified, contains the range of the population values. The field
  /// must not be present if the `count` is zero.
  public var range: Distribution.Range? = nil

  /// Defines the histogram bucket boundaries. If the distribution does not
  /// contain a histogram, then omit this field.
  public var bucketOptions: Distribution.BucketOptions? = nil

  /// The number of values in each bucket of the histogram, as described in
  /// `bucket_options`. If the distribution does not have a histogram, then omit
  /// this field. If there is a histogram, then the sum of the values in
  /// `bucket_counts` must equal the value in the `count` field of the
  /// distribution.
  ///
  /// If present, `bucket_counts` should contain N values, where N is the number
  /// of buckets specified in `bucket_options`. If you supply fewer than N
  /// values, the remaining values are assumed to be 0.
  ///
  /// The order of the values in `bucket_counts` follows the bucket numbering
  /// schemes described for the three bucket types. The first value must be the
  /// count for the underflow bucket (number 0). The next N-2 values are the
  /// counts for the finite buckets (number 1 through N-2). The N'th value in
  /// `bucket_counts` is the count for the overflow bucket (number N-1).
  public var bucketCounts: [Swift.Int64] = []

  /// Must be in increasing order of `value` field.
  public var exemplars: [Distribution.Exemplar] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Distribution`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Distribution().with { $0.count = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let count = CodingKeys(stringValue: "count")
    static let mean = CodingKeys(stringValue: "mean")
    static let sumOfSquaredDeviation = CodingKeys(stringValue: "sumOfSquaredDeviation")
    static let range = CodingKeys(stringValue: "range")
    static let bucketOptions = CodingKeys(stringValue: "bucketOptions")
    static let bucketCounts = CodingKeys(stringValue: "bucketCounts")
    static let exemplars = CodingKeys(stringValue: "exemplars")

    static let _knownKeys: Set<Swift.String> = [
      "count",
      "mean",
      "sumOfSquaredDeviation",
      "range",
      "bucketOptions",
      "bucketCounts",
      "exemplars",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .count) {
      self.count = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .mean) {
      self.mean = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .sumOfSquaredDeviation)
    {
      self.sumOfSquaredDeviation = value
    }
    self.range = try container.decodeIfPresent(Distribution.Range.self, forKey: .range)
    self.bucketOptions = try container.decodeIfPresent(
      Distribution.BucketOptions.self, forKey: .bucketOptions)
    if let value = try container.decodeIfPresent([Swift.Int64].self, forKey: .bucketCounts) {
      self.bucketCounts = value
    }
    if let value = try container.decodeIfPresent([Distribution.Exemplar].self, forKey: .exemplars) {
      self.exemplars = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.count, forKey: .count)
    try container.encode(self.mean, forKey: .mean)
    try container.encode(self.sumOfSquaredDeviation, forKey: .sumOfSquaredDeviation)
    try container.encodeIfPresent(self.range, forKey: .range)
    try container.encodeIfPresent(self.bucketOptions, forKey: .bucketOptions)
    try container.encode(self.bucketCounts, forKey: .bucketCounts)
    try container.encode(self.exemplars, forKey: .exemplars)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The range of the population values.
  public struct Range: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The minimum of the population values.
    public var min: Swift.Double = Swift.Double()

    /// The maximum of the population values.
    public var max: Swift.Double = Swift.Double()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Range`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Range().with { $0.min = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let min = CodingKeys(stringValue: "min")
      static let max = CodingKeys(stringValue: "max")

      static let _knownKeys: Set<Swift.String> = [
        "min",
        "max",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .min) {
        self.min = value
      }
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .max) {
        self.max = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.min, forKey: .min)
      try container.encode(self.max, forKey: .max)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.Distribution.Range"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// `BucketOptions` describes the bucket boundaries used to create a histogram
  /// for the distribution. The buckets can be in a linear sequence, an
  /// exponential sequence, or each bucket can be specified explicitly.
  /// `BucketOptions` does not include the number of values in each bucket.
  ///
  /// A bucket has an inclusive lower bound and exclusive upper bound for the
  /// values that are counted for that bucket. The upper bound of a bucket must
  /// be strictly greater than the lower bound. The sequence of N buckets for a
  /// distribution consists of an underflow bucket (number 0), zero or more
  /// finite buckets (number 1 through N - 2) and an overflow bucket (number N -
  /// 1). The buckets are contiguous: the lower bound of bucket i (i > 0) is the
  /// same as the upper bound of bucket i - 1. The buckets span the whole range
  /// of finite values: lower bound of the underflow bucket is -infinity and the
  /// upper bound of the overflow bucket is +infinity. The finite buckets are
  /// so-called because both bounds are finite.
  public struct BucketOptions: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Exactly one of these three fields must be set.
    public var options: OneOf_Options? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `BucketOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BucketOptions().with { $0.linearBuckets = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let linearBuckets = CodingKeys(stringValue: "linearBuckets")
      static let exponentialBuckets = CodingKeys(stringValue: "exponentialBuckets")
      static let explicitBuckets = CodingKeys(stringValue: "explicitBuckets")

      static let _knownKeys: Set<Swift.String> = [
        "linearBuckets",
        "exponentialBuckets",
        "explicitBuckets",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var options: OneOf_Options? = nil
      let optionsCheckAndSet = {
        if options != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'options'"))
        }
        options = $0
      }
      if let linearBuckets = try container.decodeIfPresent(
        Distribution.BucketOptions.Linear?.self, forKey: .linearBuckets)
      {
        try optionsCheckAndSet(.linearBuckets(linearBuckets))
      }
      if let exponentialBuckets = try container.decodeIfPresent(
        Distribution.BucketOptions.Exponential?.self, forKey: .exponentialBuckets)
      {
        try optionsCheckAndSet(.exponentialBuckets(exponentialBuckets))
      }
      if let explicitBuckets = try container.decodeIfPresent(
        Distribution.BucketOptions.Explicit?.self, forKey: .explicitBuckets)
      {
        try optionsCheckAndSet(.explicitBuckets(explicitBuckets))
      }
      self.options = options
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.options {
        switch choice {
        case .linearBuckets(let value):
          try container.encode(value, forKey: .linearBuckets)
        case .exponentialBuckets(let value):
          try container.encode(value, forKey: .exponentialBuckets)
        case .explicitBuckets(let value):
          try container.encode(value, forKey: .explicitBuckets)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Specifies a linear sequence of buckets that all have the same width
    /// (except overflow and underflow). Each bucket represents a constant
    /// absolute uncertainty on the specific value in the bucket.
    ///
    /// There are `num_finite_buckets + 2` (= N) buckets. Bucket `i` has the
    /// following boundaries:
    ///
    ///    Upper bound (0 <= i < N-1):     offset + (width * i).
    ///
    ///    Lower bound (1 <= i < N):       offset + (width * (i - 1)).
    public struct Linear: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Must be greater than 0.
      public var numFiniteBuckets: Swift.Int32 = Swift.Int32()

      /// Must be greater than 0.
      public var width: Swift.Double = Swift.Double()

      /// Lower bound of the first bucket.
      public var offset: Swift.Double = Swift.Double()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Linear`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Linear().with { $0.numFiniteBuckets = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let numFiniteBuckets = CodingKeys(stringValue: "numFiniteBuckets")
        static let width = CodingKeys(stringValue: "width")
        static let offset = CodingKeys(stringValue: "offset")

        static let _knownKeys: Set<Swift.String> = [
          "numFiniteBuckets",
          "width",
          "offset",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .numFiniteBuckets) {
          self.numFiniteBuckets = value
        }
        if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .width) {
          self.width = value
        }
        if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .offset) {
          self.offset = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.numFiniteBuckets, forKey: .numFiniteBuckets)
        try container.encode(self.width, forKey: .width)
        try container.encode(self.offset, forKey: .offset)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.api.Distribution.BucketOptions.Linear"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Specifies an exponential sequence of buckets that have a width that is
    /// proportional to the value of the lower bound. Each bucket represents a
    /// constant relative uncertainty on a specific value in the bucket.
    ///
    /// There are `num_finite_buckets + 2` (= N) buckets. Bucket `i` has the
    /// following boundaries:
    ///
    ///    Upper bound (0 <= i < N-1):     scale * (growth_factor ^ i).
    ///
    ///    Lower bound (1 <= i < N):       scale * (growth_factor ^ (i - 1)).
    public struct Exponential: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Must be greater than 0.
      public var numFiniteBuckets: Swift.Int32 = Swift.Int32()

      /// Must be greater than 1.
      public var growthFactor: Swift.Double = Swift.Double()

      /// Must be greater than 0.
      public var scale: Swift.Double = Swift.Double()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Exponential`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Exponential().with { $0.numFiniteBuckets = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let numFiniteBuckets = CodingKeys(stringValue: "numFiniteBuckets")
        static let growthFactor = CodingKeys(stringValue: "growthFactor")
        static let scale = CodingKeys(stringValue: "scale")

        static let _knownKeys: Set<Swift.String> = [
          "numFiniteBuckets",
          "growthFactor",
          "scale",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .numFiniteBuckets) {
          self.numFiniteBuckets = value
        }
        if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .growthFactor) {
          self.growthFactor = value
        }
        if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .scale) {
          self.scale = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.numFiniteBuckets, forKey: .numFiniteBuckets)
        try container.encode(self.growthFactor, forKey: .growthFactor)
        try container.encode(self.scale, forKey: .scale)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.api.Distribution.BucketOptions.Exponential"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Specifies a set of buckets with arbitrary widths.
    ///
    /// There are `size(bounds) + 1` (= N) buckets. Bucket `i` has the following
    /// boundaries:
    ///
    ///    Upper bound (0 <= i < N-1):     bounds[i]
    ///    Lower bound (1 <= i < N);       bounds[i - 1]
    ///
    /// The `bounds` field must contain at least one element. If `bounds` has
    /// only one element, then there are no finite buckets, and that single
    /// element is the common boundary of the overflow and underflow buckets.
    public struct Explicit: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The values must be monotonically increasing.
      public var bounds: [Swift.Double] = []

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Explicit`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Explicit().with { $0.bounds = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let bounds = CodingKeys(stringValue: "bounds")

        static let _knownKeys: Set<Swift.String> = [
          "bounds"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent([Swift.Double].self, forKey: .bounds) {
          self.bounds = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.bounds, forKey: .bounds)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.api.Distribution.BucketOptions.Explicit"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Exactly one of these three fields must be set.
    public enum OneOf_Options: Codable, Equatable, Sendable {
      /// The linear bucket.
      indirect case linearBuckets(Distribution.BucketOptions.Linear?)
      /// The exponential buckets.
      indirect case exponentialBuckets(Distribution.BucketOptions.Exponential?)
      /// The explicit buckets.
      indirect case explicitBuckets(Distribution.BucketOptions.Explicit?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.Distribution.BucketOptions"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Exemplars are example points that may be used to annotate aggregated
  /// distribution values. They are metadata that gives information about a
  /// particular value added to a Distribution bucket, such as a trace ID that
  /// was active when a value was added. They may contain further information,
  /// such as a example values and timestamps, origin, etc.
  public struct Exemplar: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Value of the exemplar point. This value determines to which bucket the
    /// exemplar belongs.
    public var value: Swift.Double = Swift.Double()

    /// The observation (sampling) time of the above value.
    public var timestamp: GoogleWKT.Timestamp? = nil

    /// Contextual information about the example value. Examples are:
    ///
    ///   Trace: type.googleapis.com/google.monitoring.v3.SpanContext
    ///
    ///   Literal string: type.googleapis.com/google.protobuf.StringValue
    ///
    ///   Labels dropped during aggregation:
    ///     type.googleapis.com/google.monitoring.v3.DroppedLabels
    ///
    /// There may be only a single attachment of any given message type in a
    /// single exemplar, and this is enforced by the system.
    public var attachments: [GoogleWKT.`Any`] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Exemplar`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Exemplar().with { $0.value = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let value = CodingKeys(stringValue: "value")
      static let timestamp = CodingKeys(stringValue: "timestamp")
      static let attachments = CodingKeys(stringValue: "attachments")

      static let _knownKeys: Set<Swift.String> = [
        "value",
        "timestamp",
        "attachments",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .value) {
        self.value = value
      }
      self.timestamp = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .timestamp)
      if let value = try container.decodeIfPresent([GoogleWKT.`Any`].self, forKey: .attachments) {
        self.attachments = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.value, forKey: .value)
      try container.encodeIfPresent(self.timestamp, forKey: .timestamp)
      try container.encode(self.attachments, forKey: .attachments)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.Distribution.Exemplar"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.Distribution"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
