// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A documentation rule provides information about individual API elements.
public struct DocumentationRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The selector is a comma-separated list of patterns for any element such as
  /// a method, a field, an enum value. Each pattern is a qualified name of the
  /// element which may end in "*", indicating a wildcard. Wildcards are only
  /// allowed at the end and for a whole component of the qualified name,
  /// i.e. "foo.*" is ok, but not "foo.b*" or "foo.*.bar". A wildcard will match
  /// one or more components. To specify a default for all applicable elements,
  /// the whole pattern "*" is used.
  public var selector: Swift.String = Swift.String()

  /// Description of the selected proto element (e.g. a message, a method, a
  /// 'service' definition, or a field). Defaults to leading & trailing comments
  /// taken from the proto source definition of the proto element.
  public var description: Swift.String = Swift.String()

  /// Deprecation description of the selected element(s). It can be provided if
  /// an element is marked as `deprecated`.
  public var deprecationDescription: Swift.String = Swift.String()

  /// Initialize a new instance of `DocumentationRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DocumentationRule().with { $0.selector = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.api.DocumentationRule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
