// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Settings for Dotnet client libraries.
public struct DotnetSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Some settings.
  public var common: CommonLanguageSettings?

  /// Map from original service names to renamed versions.
  /// This is used when the default generated types
  /// would cause a naming conflict. (Neither name is
  /// fully-qualified.)
  /// Example: Subscriber to SubscriberServiceApi.
  public var renamedServices: [Swift.String: Swift.String]

  /// Map from full resource types to the effective short name
  /// for the resource. This is used when otherwise resource
  /// named from different services would cause naming collisions.
  /// Example entry:
  /// "datalabeling.googleapis.com/Dataset": "DataLabelingDataset"
  public var renamedResources: [Swift.String: Swift.String]

  /// List of full resource types to ignore during generation.
  /// This is typically used for API-specific Location resources,
  /// which should be handled by the generator as if they were actually
  /// the common Location resources.
  /// Example entry: "documentai.googleapis.com/Location"
  public var ignoredResources: [Swift.String]

  /// Namespaces which must be aliased in snippets due to
  /// a known (but non-generator-predictable) naming collision
  public var forcedNamespaceAliases: [Swift.String]

  /// Method signatures (in the form "service.method(signature)")
  /// which are provided separately, so shouldn't be generated.
  /// Snippets *calling* these methods are still generated, however.
  public var handwrittenSignatures: [Swift.String]

  /// Initialize a new instance of `DotnetSettings`.
  public init(
    common: CommonLanguageSettings? = nil,
    renamedServices: [Swift.String: Swift.String] = [:],
    renamedResources: [Swift.String: Swift.String] = [:],
    ignoredResources: [Swift.String] = [],
    forcedNamespaceAliases: [Swift.String] = [],
    handwrittenSignatures: [Swift.String] = [],
  ) {
    self.common = common
    self.renamedServices = renamedServices
    self.renamedResources = renamedResources
    self.ignoredResources = ignoredResources
    self.forcedNamespaceAliases = forcedNamespaceAliases
    self.handwrittenSignatures = handwrittenSignatures
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.api.DotnetSettings" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
