// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Defines the supported values for `google.rpc.ErrorInfo.reason` for the
/// `googleapis.com` error domain. This error domain is reserved for [Service
/// Infrastructure](https://cloud.google.com/service-infrastructure/docs/overview).
/// For each error info of this domain, the metadata key "service" refers to the
/// logical identifier of an API service, such as "pubsub.googleapis.com". The
/// "consumer" refers to the entity that consumes an API Service. It typically is
/// a Google project that owns the client application or the server resource,
/// such as "projects/123". Other metadata keys are specific to each error
/// reason. For more information, see the definition of the specific error
/// reason.
public enum ErrorReason: Codable, Equatable, Sendable {
  /// Do not use this default value.
  case unspecified
  /// The request is calling a disabled service for a consumer.
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" contacting
  /// "pubsub.googleapis.com" service which is disabled:
  ///
  ///     { "reason": "SERVICE_DISABLED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "pubsub.googleapis.com"
  ///       }
  ///     }
  ///
  /// This response indicates the "pubsub.googleapis.com" has been disabled in
  /// "projects/123".
  case serviceDisabled
  /// The request whose associated billing account is disabled.
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" fails to contact
  /// "pubsub.googleapis.com" service because the associated billing account is
  /// disabled:
  ///
  ///     { "reason": "BILLING_DISABLED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "pubsub.googleapis.com"
  ///       }
  ///     }
  ///
  /// This response indicates the billing account associated has been disabled.
  case billingDisabled
  /// The request is denied because the provided [API
  /// key](https://cloud.google.com/docs/authentication/api-keys) is invalid. It
  /// may be in a bad format, cannot be found, or has been expired).
  ///
  /// Example of an ErrorInfo when the request is contacting
  /// "storage.googleapis.com" service with an invalid API key:
  ///
  ///     { "reason": "API_KEY_INVALID",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "service": "storage.googleapis.com",
  ///       }
  ///     }
  case apiKeyInvalid
  /// The request is denied because it violates [API key API
  /// restrictions](https://cloud.google.com/docs/authentication/api-keys#adding_api_restrictions).
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" fails to call the
  /// "storage.googleapis.com" service because this service is restricted in the
  /// API key:
  ///
  ///     { "reason": "API_KEY_SERVICE_BLOCKED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "storage.googleapis.com"
  ///       }
  ///     }
  case apiKeyServiceBlocked
  /// The request is denied because there is not enough rate quota for the
  /// consumer.
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" fails to contact
  /// "pubsub.googleapis.com" service because consumer's rate quota usage has
  /// reached the maximum value set for the quota limit
  /// "ReadsPerMinutePerProject" on the quota metric
  /// "pubsub.googleapis.com/read_requests":
  ///
  ///     { "reason": "RATE_LIMIT_EXCEEDED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "pubsub.googleapis.com",
  ///         "quota_metric": "pubsub.googleapis.com/read_requests",
  ///         "quota_limit": "ReadsPerMinutePerProject"
  ///       }
  ///     }
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" checks quota on
  /// the service "dataflow.googleapis.com" and hits the organization quota
  /// limit "DefaultRequestsPerMinutePerOrganization" on the metric
  /// "dataflow.googleapis.com/default_requests".
  ///
  ///     { "reason": "RATE_LIMIT_EXCEEDED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "dataflow.googleapis.com",
  ///         "quota_metric": "dataflow.googleapis.com/default_requests",
  ///         "quota_limit": "DefaultRequestsPerMinutePerOrganization"
  ///       }
  ///     }
  case rateLimitExceeded
  /// The request is denied because there is not enough resource quota for the
  /// consumer.
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" fails to contact
  /// "compute.googleapis.com" service because consumer's resource quota usage
  /// has reached the maximum value set for the quota limit "VMsPerProject"
  /// on the quota metric "compute.googleapis.com/vms":
  ///
  ///     { "reason": "RESOURCE_QUOTA_EXCEEDED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "compute.googleapis.com",
  ///         "quota_metric": "compute.googleapis.com/vms",
  ///         "quota_limit": "VMsPerProject"
  ///       }
  ///     }
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" checks resource
  /// quota on the service "dataflow.googleapis.com" and hits the organization
  /// quota limit "jobs-per-organization" on the metric
  /// "dataflow.googleapis.com/job_count".
  ///
  ///     { "reason": "RESOURCE_QUOTA_EXCEEDED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "dataflow.googleapis.com",
  ///         "quota_metric": "dataflow.googleapis.com/job_count",
  ///         "quota_limit": "jobs-per-organization"
  ///       }
  ///     }
  case resourceQuotaExceeded
  /// The request is denied because it violates [API key HTTP
  /// restrictions](https://cloud.google.com/docs/authentication/api-keys#adding_http_restrictions).
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" fails to call
  /// "storage.googleapis.com" service because the http referrer of the request
  /// violates API key HTTP restrictions:
  ///
  ///     { "reason": "API_KEY_HTTP_REFERRER_BLOCKED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "storage.googleapis.com",
  ///       }
  ///     }
  case apiKeyHttpReferrerBlocked
  /// The request is denied because it violates [API key IP address
  /// restrictions](https://cloud.google.com/docs/authentication/api-keys#adding_application_restrictions).
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" fails to call
  /// "storage.googleapis.com" service because the caller IP of the request
  /// violates API key IP address restrictions:
  ///
  ///     { "reason": "API_KEY_IP_ADDRESS_BLOCKED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "storage.googleapis.com",
  ///       }
  ///     }
  case apiKeyIpAddressBlocked
  /// The request is denied because it violates [API key Android application
  /// restrictions](https://cloud.google.com/docs/authentication/api-keys#adding_application_restrictions).
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" fails to call
  /// "storage.googleapis.com" service because the request from the Android apps
  /// violates the API key Android application restrictions:
  ///
  ///     { "reason": "API_KEY_ANDROID_APP_BLOCKED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "storage.googleapis.com"
  ///       }
  ///     }
  case apiKeyAndroidAppBlocked
  /// The request whose associated billing account address is in a tax restricted
  /// location, violates the local tax restrictions when creating resources in
  /// the restricted region.
  ///
  /// Example of an ErrorInfo when creating the Cloud Storage Bucket in the
  /// container "projects/123" under a tax restricted region
  /// "locations/asia-northeast3":
  ///
  ///     { "reason": "LOCATION_TAX_POLICY_VIOLATED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "storage.googleapis.com",
  ///         "location": "locations/asia-northeast3"
  ///       }
  ///     }
  ///
  /// This response indicates creating the Cloud Storage Bucket in
  /// "locations/asia-northeast3" violates the location tax restriction.
  case locationTaxPolicyViolated
  /// The request is denied because the caller does not have required permission
  /// on the user project "projects/123" or the user project is invalid. For more
  /// information, check the [userProject System
  /// Parameters](https://cloud.google.com/apis/docs/system-parameters).
  ///
  /// Example of an ErrorInfo when the caller is calling Cloud Storage service
  /// with insufficient permissions on the user project:
  ///
  ///     { "reason": "USER_PROJECT_DENIED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "storage.googleapis.com"
  ///       }
  ///     }
  case userProjectDenied
  /// The request is denied because the consumer "projects/123" is suspended due
  /// to Terms of Service(Tos) violations. Check [Project suspension
  /// guidelines](https://cloud.google.com/resource-manager/docs/project-suspension-guidelines)
  /// for more information.
  ///
  /// Example of an ErrorInfo when calling Cloud Storage service with the
  /// suspended consumer "projects/123":
  ///
  ///     { "reason": "CONSUMER_SUSPENDED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "storage.googleapis.com"
  ///       }
  ///     }
  case consumerSuspended
  /// The request is denied because it violates [API key iOS application
  /// restrictions](https://cloud.google.com/docs/authentication/api-keys#adding_application_restrictions).
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" fails to call
  /// "storage.googleapis.com" service because the request from the iOS apps
  /// violates the API key iOS application restrictions:
  ///
  ///     { "reason": "API_KEY_IOS_APP_BLOCKED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "storage.googleapis.com"
  ///       }
  ///     }
  case apiKeyIosAppBlocked
  /// The request is denied because the associated consumer is invalid. It may be
  /// in a bad format, cannot be found, or have been deleted.
  ///
  /// Example of an ErrorInfo when calling Cloud Storage service with the
  /// invalid consumer "projects/123":
  ///
  ///     { "reason": "CONSUMER_INVALID",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "storage.googleapis.com"
  ///       }
  ///     }
  case consumerInvalid
  /// The request is denied because it violates [VPC Service
  /// Controls](https://cloud.google.com/vpc-service-controls/docs/overview).
  /// The 'uid' field is a random generated identifier that customer can use it
  /// to search the audit log for a request rejected by VPC Service Controls. For
  /// more information, please refer [VPC Service Controls
  /// Troubleshooting](https://cloud.google.com/vpc-service-controls/docs/troubleshooting#unique-id)
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" fails to call
  /// Cloud Storage service because the request is prohibited by the VPC Service
  /// Controls.
  ///
  ///     { "reason": "SECURITY_POLICY_VIOLATED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "uid": "123456789abcde",
  ///         "consumer": "projects/123",
  ///         "service": "storage.googleapis.com"
  ///       }
  ///     }
  case securityPolicyViolated
  /// The request is denied because the provided access token has expired.
  ///
  /// Example of an ErrorInfo when the request is calling Cloud Storage service
  /// with an expired access token:
  ///
  ///     { "reason": "ACCESS_TOKEN_EXPIRED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "service": "storage.googleapis.com",
  ///         "method": "google.storage.v1.Storage.GetObject"
  ///       }
  ///     }
  case accessTokenExpired
  /// The request is denied because the provided access token doesn't have at
  /// least one of the acceptable scopes required for the API. Please check
  /// [OAuth 2.0 Scopes for Google
  /// APIs](https://developers.google.com/identity/protocols/oauth2/scopes) for
  /// the list of the OAuth 2.0 scopes that you might need to request to access
  /// the API.
  ///
  /// Example of an ErrorInfo when the request is calling Cloud Storage service
  /// with an access token that is missing required scopes:
  ///
  ///     { "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "service": "storage.googleapis.com",
  ///         "method": "google.storage.v1.Storage.GetObject"
  ///       }
  ///     }
  case accessTokenScopeInsufficient
  /// The request is denied because the account associated with the provided
  /// access token is in an invalid state, such as disabled or deleted.
  /// For more information, see https://cloud.google.com/docs/authentication.
  ///
  /// Warning: For privacy reasons, the server may not be able to disclose the
  /// email address for some accounts. The client MUST NOT depend on the
  /// availability of the `email` attribute.
  ///
  /// Example of an ErrorInfo when the request is to the Cloud Storage API with
  /// an access token that is associated with a disabled or deleted [service
  /// account](http://cloud/iam/docs/service-accounts):
  ///
  ///     { "reason": "ACCOUNT_STATE_INVALID",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "service": "storage.googleapis.com",
  ///         "method": "google.storage.v1.Storage.GetObject",
  ///         "email": "user@123.iam.gserviceaccount.com"
  ///       }
  ///     }
  case accountStateInvalid
  /// The request is denied because the type of the provided access token is not
  /// supported by the API being called.
  ///
  /// Example of an ErrorInfo when the request is to the Cloud Storage API with
  /// an unsupported token type.
  ///
  ///     { "reason": "ACCESS_TOKEN_TYPE_UNSUPPORTED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "service": "storage.googleapis.com",
  ///         "method": "google.storage.v1.Storage.GetObject"
  ///       }
  ///     }
  case accessTokenTypeUnsupported
  /// The request is denied because the request doesn't have any authentication
  /// credentials. For more information regarding the supported authentication
  /// strategies for Google Cloud APIs, see
  /// https://cloud.google.com/docs/authentication.
  ///
  /// Example of an ErrorInfo when the request is to the Cloud Storage API
  /// without any authentication credentials.
  ///
  ///     { "reason": "CREDENTIALS_MISSING",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "service": "storage.googleapis.com",
  ///         "method": "google.storage.v1.Storage.GetObject"
  ///       }
  ///     }
  case credentialsMissing
  /// The request is denied because the provided project owning the resource
  /// which acts as the [API
  /// consumer](https://cloud.google.com/apis/design/glossary#api_consumer) is
  /// invalid. It may be in a bad format or empty.
  ///
  /// Example of an ErrorInfo when the request is to the Cloud Functions API,
  /// but the offered resource project in the request in a bad format which can't
  /// perform the ListFunctions method.
  ///
  ///     { "reason": "RESOURCE_PROJECT_INVALID",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "service": "cloudfunctions.googleapis.com",
  ///         "method":
  ///         "google.cloud.functions.v1.CloudFunctionsService.ListFunctions"
  ///       }
  ///     }
  case resourceProjectInvalid
  /// The request is denied because the provided session cookie is missing,
  /// invalid or failed to decode.
  ///
  /// Example of an ErrorInfo when the request is calling Cloud Storage service
  /// with a SID cookie which can't be decoded.
  ///
  ///     { "reason": "SESSION_COOKIE_INVALID",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "service": "storage.googleapis.com",
  ///         "method": "google.storage.v1.Storage.GetObject",
  ///         "cookie": "SID"
  ///       }
  ///     }
  case sessionCookieInvalid
  /// The request is denied because the user is from a Google Workspace customer
  /// that blocks their users from accessing a particular service.
  ///
  /// Example scenario: https://support.google.com/a/answer/9197205?hl=en
  ///
  /// Example of an ErrorInfo when access to Google Cloud Storage service is
  /// blocked by the Google Workspace administrator:
  ///
  ///     { "reason": "USER_BLOCKED_BY_ADMIN",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "service": "storage.googleapis.com",
  ///         "method": "google.storage.v1.Storage.GetObject",
  ///       }
  ///     }
  case userBlockedByAdmin
  /// The request is denied because the resource service usage is restricted
  /// by administrators according to the organization policy constraint.
  /// For more information see
  /// https://cloud.google.com/resource-manager/docs/organization-policy/restricting-services.
  ///
  /// Example of an ErrorInfo when access to Google Cloud Storage service is
  /// restricted by Resource Usage Restriction policy:
  ///
  ///     { "reason": "RESOURCE_USAGE_RESTRICTION_VIOLATED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/project-123",
  ///         "service": "storage.googleapis.com"
  ///       }
  ///     }
  case resourceUsageRestrictionViolated
  /// Unimplemented. Do not use.
  ///
  /// The request is denied because it contains unsupported system parameters in
  /// URL query parameters or HTTP headers. For more information,
  /// see https://cloud.google.com/apis/docs/system-parameters
  ///
  /// Example of an ErrorInfo when access "pubsub.googleapis.com" service with
  /// a request header of "x-goog-user-ip":
  ///
  ///     { "reason": "SYSTEM_PARAMETER_UNSUPPORTED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "service": "pubsub.googleapis.com"
  ///         "parameter": "x-goog-user-ip"
  ///       }
  ///     }
  case systemParameterUnsupported
  /// The request is denied because it violates Org Restriction: the requested
  /// resource does not belong to allowed organizations specified in
  /// "X-Goog-Allowed-Resources" header.
  ///
  /// Example of an ErrorInfo when accessing a GCP resource that is restricted by
  /// Org Restriction for "pubsub.googleapis.com" service.
  ///
  /// {
  ///   reason: "ORG_RESTRICTION_VIOLATION"
  ///   domain: "googleapis.com"
  ///   metadata {
  ///     "consumer":"projects/123456"
  ///     "service": "pubsub.googleapis.com"
  ///   }
  /// }
  case orgRestrictionViolation
  /// The request is denied because "X-Goog-Allowed-Resources" header is in a bad
  /// format.
  ///
  /// Example of an ErrorInfo when
  /// accessing "pubsub.googleapis.com" service with an invalid
  /// "X-Goog-Allowed-Resources" request header.
  ///
  /// {
  ///   reason: "ORG_RESTRICTION_HEADER_INVALID"
  ///   domain: "googleapis.com"
  ///   metadata {
  ///     "consumer":"projects/123456"
  ///     "service": "pubsub.googleapis.com"
  ///   }
  /// }
  case orgRestrictionHeaderInvalid
  /// Unimplemented. Do not use.
  ///
  /// The request is calling a service that is not visible to the consumer.
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" contacting
  ///  "pubsub.googleapis.com" service which is not visible to the consumer.
  ///
  ///     { "reason": "SERVICE_NOT_VISIBLE",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "pubsub.googleapis.com"
  ///       }
  ///     }
  ///
  /// This response indicates the "pubsub.googleapis.com" is not visible to
  /// "projects/123" (or it may not exist).
  case serviceNotVisible
  /// The request is related to a project for which GCP access is suspended.
  ///
  /// Example of an ErrorInfo when the consumer "projects/123" fails to contact
  /// "pubsub.googleapis.com" service because GCP access is suspended:
  ///
  ///     { "reason": "GCP_SUSPENDED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "pubsub.googleapis.com"
  ///       }
  ///     }
  ///
  /// This response indicates the associated GCP account has been suspended.
  case gcpSuspended
  /// The request violates the location policies when creating resources in
  /// the restricted region.
  ///
  /// Example of an ErrorInfo when creating the Cloud Storage Bucket by
  /// "projects/123" for service storage.googleapis.com:
  ///
  ///     { "reason": "LOCATION_POLICY_VIOLATED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "storage.googleapis.com",
  ///       }
  ///     }
  ///
  /// This response indicates creating the Cloud Storage Bucket in
  /// "locations/asia-northeast3" violates at least one location policy.
  /// The troubleshooting guidance is provided in the Help links.
  case locationPolicyViolated
  /// The request is denied because origin request header is missing.
  ///
  /// Example of an ErrorInfo when
  /// accessing "pubsub.googleapis.com" service with an empty "Origin" request
  /// header.
  ///
  /// {
  ///   reason: "MISSING_ORIGIN"
  ///   domain: "googleapis.com"
  ///   metadata {
  ///     "consumer":"projects/123456"
  ///     "service": "pubsub.googleapis.com"
  ///   }
  /// }
  case missingOrigin
  /// The request is denied because the request contains more than one credential
  /// type that are individually acceptable, but not together. The customer
  /// should retry their request with only one set of credentials.
  ///
  /// Example of an ErrorInfo when
  /// accessing "pubsub.googleapis.com" service with overloaded credentials.
  ///
  /// {
  ///   reason: "OVERLOADED_CREDENTIALS"
  ///   domain: "googleapis.com"
  ///   metadata {
  ///     "consumer":"projects/123456"
  ///     "service": "pubsub.googleapis.com"
  ///   }
  /// }
  case overloadedCredentials
  /// The request whose associated location violates the location org policy
  /// restrictions when creating resources in the restricted region.
  ///
  /// Example of an ErrorInfo when creating the Cloud Storage Bucket in the
  /// container "projects/123" under a restricted region
  /// "locations/asia-northeast3":
  ///
  ///     {
  ///       "reason": "LOCATION_ORG_POLICY_VIOLATED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "resource": "projects/123",
  ///         "location": "locations/asia-northeast3"
  ///       }
  ///     }
  ///
  /// This response indicates creating the Cloud Storage Bucket in
  /// "locations/asia-northeast3" violates the location org policy restriction.
  case locationOrgPolicyViolated
  /// The request is denied because it access data of regulated customers using
  /// TLS 1.0 and 1.1.
  ///
  /// Example of an ErrorInfo when accessing a GCP resource "projects/123" that
  /// is restricted by TLS Version Restriction for "pubsub.googleapis.com"
  /// service.
  ///
  ///     {
  ///       "reason": "TLS_ORG_POLICY_VIOLATED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "service": "pubsub.googleapis.com"
  ///         "resource": "projects/123",
  ///         "policyName": "constraints/gcp.restrictTLSVersion",
  ///         "tlsVersion": "TLS_VERSION_1"
  ///       }
  ///     }
  case tlsOrgPolicyViolated
  /// The request is denied because the associated project has exceeded the
  /// emulator quota limit.
  ///
  /// Example of an ErrorInfo when the associated "projects/123" has exceeded the
  /// emulator quota limit.
  ///
  ///     {
  ///       "reason": "EMULATOR_QUOTA_EXCEEDED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///           "service": "pubsub.googleapis.com"
  ///           "consumer": "projects/123"
  ///        }
  ///     }
  case emulatorQuotaExceeded
  /// The request is denied because the associated application credential header
  /// is invalid for an Android applications.
  ///
  /// Example of an ErrorInfo when the request from an Android application to the
  /// "pubsub.googleapis.com" with an invalid application credential header.
  ///
  ///     {
  ///       "reason": "CREDENTIAL_ANDROID_APP_INVALID",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///           "service": "pubsub.googleapis.com"
  ///        }
  ///     }
  case credentialAndroidAppInvalid
  /// The request is denied because IAM permission on resource is denied.
  ///
  /// Example of an ErrorInfo when the IAM permission `aiplatform.datasets.list`
  /// is denied on resource `projects/123`.
  ///
  ///     {
  ///       "reason": "IAM_PERMISSION_DENIED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///           "resource": "projects/123"
  ///           "permission": "aiplatform.datasets.list"
  ///        }
  ///     }
  case iamPermissionDenied
  /// The request is denied because it contains the invalid JWT token.
  ///
  /// Example of an ErrorInfo when the request contains an invalid JWT token for
  /// service `storage.googleapis.com`.
  ///
  ///     {
  ///       "reason": "JWT_TOKEN_INVALID",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///           "service": "storage.googleapis.com"
  ///        }
  ///     }
  case jwtTokenInvalid
  /// The request is denied because it contains credential with type that is
  /// unsupported.
  ///
  /// Example of an ErrorInfo when the request contains an unsupported credential
  /// type for service `storage.googleapis.com`.
  ///
  ///     {
  ///       "reason": "CREDENTIAL_TYPE_UNSUPPORTED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///           "service": "storage.googleapis.com"
  ///        }
  ///     }
  case credentialTypeUnsupported
  /// The request is denied because it contains unsupported account type.
  ///
  /// Example of an ErrorInfo when the request contains an unsupported account
  /// type for service `storage.googleapis.com`.
  ///
  ///     {
  ///       "reason": "ACCOUNT_TYPE_UNSUPPORTED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///           "service": "storage.googleapis.com"
  ///        }
  ///     }
  case accountTypeUnsupported
  /// The request is denied because the API endpoint is restricted by
  /// administrators according to the organization policy constraint.
  /// For more information see
  /// https://cloud.google.com/assured-workloads/docs/restrict-endpoint-usage.
  ///
  /// Example of an ErrorInfo when access to Google Cloud Storage service is
  /// restricted by Restrict Endpoint Usage policy:
  ///
  ///     {
  ///       "reason": "ENDPOINT_USAGE_RESTRICTION_VIOLATED",
  ///       "domain": "googleapis.com/policies/endpointUsageRestriction",
  ///       "metadata": {
  ///         "policy_name": "constraints/gcp.restrictEndpointUsage",
  ///         "checked_value": "storage.googleapis.com"
  ///         "consumer": "organization/123"
  ///         "service": "storage.googleapis.com"
  ///        }
  ///     }
  case endpointUsageRestrictionViolated
  /// The request is denied because the TLS Cipher Suite is restricted by
  /// administrators according to the organization policy constraint.
  /// For more information see
  /// https://cloud.google.com/assured-workloads/docs/restrict-tls-cipher-suites
  ///
  /// Example of an ErrorInfo when access to Google Cloud BigQuery service is
  /// restricted by Restrict TLS Cipher Suites policy:
  ///
  ///     {
  ///       "reason": "TLS_CIPHER_RESTRICTION_VIOLATED",
  ///       "domain": "googleapis.com/policies/tlsCipherRestriction",
  ///       "metadata": {
  ///         "policy_name": "constraints/gcp.restrictTLSCipherSuites",
  ///         "checked_value": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  ///         "consumer": "organization/123"
  ///         "service": "bigquery.googleapis.com"
  ///        }
  ///     }
  case tlsCipherRestrictionViolated
  /// The request is denied because the MCP activation check fails.
  ///
  /// Example of an ErrorInfo when the container "projects/123" contacting
  /// "pubsub.googleapis.com" service which is disabled by MCP:
  ///
  ///     { "reason": "MCP_SERVER_DISABLED",
  ///       "domain": "googleapis.com",
  ///       "metadata": {
  ///         "consumer": "projects/123",
  ///         "service": "pubsub.googleapis.com"
  ///       }
  ///     }
  ///
  /// This response indicates the "pubsub.googleapis.com" has been disabled in
  /// "projects/123" for MCP.
  case mcpServerDisabled
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .serviceDisabled: return 1
    case .billingDisabled: return 2
    case .apiKeyInvalid: return 3
    case .apiKeyServiceBlocked: return 4
    case .rateLimitExceeded: return 5
    case .resourceQuotaExceeded: return 6
    case .apiKeyHttpReferrerBlocked: return 7
    case .apiKeyIpAddressBlocked: return 8
    case .apiKeyAndroidAppBlocked: return 9
    case .locationTaxPolicyViolated: return 10
    case .userProjectDenied: return 11
    case .consumerSuspended: return 12
    case .apiKeyIosAppBlocked: return 13
    case .consumerInvalid: return 14
    case .securityPolicyViolated: return 15
    case .accessTokenExpired: return 16
    case .accessTokenScopeInsufficient: return 17
    case .accountStateInvalid: return 18
    case .accessTokenTypeUnsupported: return 19
    case .credentialsMissing: return 20
    case .resourceProjectInvalid: return 21
    case .sessionCookieInvalid: return 23
    case .userBlockedByAdmin: return 24
    case .resourceUsageRestrictionViolated: return 25
    case .systemParameterUnsupported: return 26
    case .orgRestrictionViolation: return 27
    case .orgRestrictionHeaderInvalid: return 28
    case .serviceNotVisible: return 29
    case .gcpSuspended: return 30
    case .locationPolicyViolated: return 31
    case .missingOrigin: return 33
    case .overloadedCredentials: return 34
    case .locationOrgPolicyViolated: return 35
    case .tlsOrgPolicyViolated: return 36
    case .emulatorQuotaExceeded: return 38
    case .credentialAndroidAppInvalid: return 39
    case .iamPermissionDenied: return 41
    case .jwtTokenInvalid: return 42
    case .credentialTypeUnsupported: return 43
    case .accountTypeUnsupported: return 44
    case .endpointUsageRestrictionViolated: return 45
    case .tlsCipherRestrictionViolated: return 46
    case .mcpServerDisabled: return 47
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: String? {
    switch self {
    case .unspecified: return "ERROR_REASON_UNSPECIFIED"
    case .serviceDisabled: return "SERVICE_DISABLED"
    case .billingDisabled: return "BILLING_DISABLED"
    case .apiKeyInvalid: return "API_KEY_INVALID"
    case .apiKeyServiceBlocked: return "API_KEY_SERVICE_BLOCKED"
    case .rateLimitExceeded: return "RATE_LIMIT_EXCEEDED"
    case .resourceQuotaExceeded: return "RESOURCE_QUOTA_EXCEEDED"
    case .apiKeyHttpReferrerBlocked: return "API_KEY_HTTP_REFERRER_BLOCKED"
    case .apiKeyIpAddressBlocked: return "API_KEY_IP_ADDRESS_BLOCKED"
    case .apiKeyAndroidAppBlocked: return "API_KEY_ANDROID_APP_BLOCKED"
    case .locationTaxPolicyViolated: return "LOCATION_TAX_POLICY_VIOLATED"
    case .userProjectDenied: return "USER_PROJECT_DENIED"
    case .consumerSuspended: return "CONSUMER_SUSPENDED"
    case .apiKeyIosAppBlocked: return "API_KEY_IOS_APP_BLOCKED"
    case .consumerInvalid: return "CONSUMER_INVALID"
    case .securityPolicyViolated: return "SECURITY_POLICY_VIOLATED"
    case .accessTokenExpired: return "ACCESS_TOKEN_EXPIRED"
    case .accessTokenScopeInsufficient: return "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
    case .accountStateInvalid: return "ACCOUNT_STATE_INVALID"
    case .accessTokenTypeUnsupported: return "ACCESS_TOKEN_TYPE_UNSUPPORTED"
    case .credentialsMissing: return "CREDENTIALS_MISSING"
    case .resourceProjectInvalid: return "RESOURCE_PROJECT_INVALID"
    case .sessionCookieInvalid: return "SESSION_COOKIE_INVALID"
    case .userBlockedByAdmin: return "USER_BLOCKED_BY_ADMIN"
    case .resourceUsageRestrictionViolated: return "RESOURCE_USAGE_RESTRICTION_VIOLATED"
    case .systemParameterUnsupported: return "SYSTEM_PARAMETER_UNSUPPORTED"
    case .orgRestrictionViolation: return "ORG_RESTRICTION_VIOLATION"
    case .orgRestrictionHeaderInvalid: return "ORG_RESTRICTION_HEADER_INVALID"
    case .serviceNotVisible: return "SERVICE_NOT_VISIBLE"
    case .gcpSuspended: return "GCP_SUSPENDED"
    case .locationPolicyViolated: return "LOCATION_POLICY_VIOLATED"
    case .missingOrigin: return "MISSING_ORIGIN"
    case .overloadedCredentials: return "OVERLOADED_CREDENTIALS"
    case .locationOrgPolicyViolated: return "LOCATION_ORG_POLICY_VIOLATED"
    case .tlsOrgPolicyViolated: return "TLS_ORG_POLICY_VIOLATED"
    case .emulatorQuotaExceeded: return "EMULATOR_QUOTA_EXCEEDED"
    case .credentialAndroidAppInvalid: return "CREDENTIAL_ANDROID_APP_INVALID"
    case .iamPermissionDenied: return "IAM_PERMISSION_DENIED"
    case .jwtTokenInvalid: return "JWT_TOKEN_INVALID"
    case .credentialTypeUnsupported: return "CREDENTIAL_TYPE_UNSUPPORTED"
    case .accountTypeUnsupported: return "ACCOUNT_TYPE_UNSUPPORTED"
    case .endpointUsageRestrictionViolated: return "ENDPOINT_USAGE_RESTRICTION_VIOLATED"
    case .tlsCipherRestrictionViolated: return "TLS_CIPHER_RESTRICTION_VIOLATED"
    case .mcpServerDisabled: return "MCP_SERVER_DISABLED"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: String) {
    switch stringValue {
    case "ERROR_REASON_UNSPECIFIED": self = .unspecified
    case "SERVICE_DISABLED": self = .serviceDisabled
    case "BILLING_DISABLED": self = .billingDisabled
    case "API_KEY_INVALID": self = .apiKeyInvalid
    case "API_KEY_SERVICE_BLOCKED": self = .apiKeyServiceBlocked
    case "API_KEY_HTTP_REFERRER_BLOCKED": self = .apiKeyHttpReferrerBlocked
    case "API_KEY_IP_ADDRESS_BLOCKED": self = .apiKeyIpAddressBlocked
    case "API_KEY_ANDROID_APP_BLOCKED": self = .apiKeyAndroidAppBlocked
    case "API_KEY_IOS_APP_BLOCKED": self = .apiKeyIosAppBlocked
    case "RATE_LIMIT_EXCEEDED": self = .rateLimitExceeded
    case "RESOURCE_QUOTA_EXCEEDED": self = .resourceQuotaExceeded
    case "LOCATION_TAX_POLICY_VIOLATED": self = .locationTaxPolicyViolated
    case "USER_PROJECT_DENIED": self = .userProjectDenied
    case "CONSUMER_SUSPENDED": self = .consumerSuspended
    case "CONSUMER_INVALID": self = .consumerInvalid
    case "SECURITY_POLICY_VIOLATED": self = .securityPolicyViolated
    case "ACCESS_TOKEN_EXPIRED": self = .accessTokenExpired
    case "ACCESS_TOKEN_SCOPE_INSUFFICIENT": self = .accessTokenScopeInsufficient
    case "ACCOUNT_STATE_INVALID": self = .accountStateInvalid
    case "ACCESS_TOKEN_TYPE_UNSUPPORTED": self = .accessTokenTypeUnsupported
    case "CREDENTIALS_MISSING": self = .credentialsMissing
    case "RESOURCE_PROJECT_INVALID": self = .resourceProjectInvalid
    case "SESSION_COOKIE_INVALID": self = .sessionCookieInvalid
    case "USER_BLOCKED_BY_ADMIN": self = .userBlockedByAdmin
    case "RESOURCE_USAGE_RESTRICTION_VIOLATED": self = .resourceUsageRestrictionViolated
    case "SYSTEM_PARAMETER_UNSUPPORTED": self = .systemParameterUnsupported
    case "ORG_RESTRICTION_VIOLATION": self = .orgRestrictionViolation
    case "ORG_RESTRICTION_HEADER_INVALID": self = .orgRestrictionHeaderInvalid
    case "SERVICE_NOT_VISIBLE": self = .serviceNotVisible
    case "GCP_SUSPENDED": self = .gcpSuspended
    case "LOCATION_POLICY_VIOLATED": self = .locationPolicyViolated
    case "MISSING_ORIGIN": self = .missingOrigin
    case "OVERLOADED_CREDENTIALS": self = .overloadedCredentials
    case "LOCATION_ORG_POLICY_VIOLATED": self = .locationOrgPolicyViolated
    case "TLS_ORG_POLICY_VIOLATED": self = .tlsOrgPolicyViolated
    case "EMULATOR_QUOTA_EXCEEDED": self = .emulatorQuotaExceeded
    case "CREDENTIAL_ANDROID_APP_INVALID": self = .credentialAndroidAppInvalid
    case "IAM_PERMISSION_DENIED": self = .iamPermissionDenied
    case "JWT_TOKEN_INVALID": self = .jwtTokenInvalid
    case "CREDENTIAL_TYPE_UNSUPPORTED": self = .credentialTypeUnsupported
    case "ACCOUNT_TYPE_UNSUPPORTED": self = .accountTypeUnsupported
    case "ENDPOINT_USAGE_RESTRICTION_VIOLATED": self = .endpointUsageRestrictionViolated
    case "TLS_CIPHER_RESTRICTION_VIOLATED": self = .tlsCipherRestrictionViolated
    case "MCP_SERVER_DISABLED": self = .mcpServerDisabled
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .serviceDisabled
    case 2: self = .billingDisabled
    case 3: self = .apiKeyInvalid
    case 4: self = .apiKeyServiceBlocked
    case 7: self = .apiKeyHttpReferrerBlocked
    case 8: self = .apiKeyIpAddressBlocked
    case 9: self = .apiKeyAndroidAppBlocked
    case 13: self = .apiKeyIosAppBlocked
    case 5: self = .rateLimitExceeded
    case 6: self = .resourceQuotaExceeded
    case 10: self = .locationTaxPolicyViolated
    case 11: self = .userProjectDenied
    case 12: self = .consumerSuspended
    case 14: self = .consumerInvalid
    case 15: self = .securityPolicyViolated
    case 16: self = .accessTokenExpired
    case 17: self = .accessTokenScopeInsufficient
    case 18: self = .accountStateInvalid
    case 19: self = .accessTokenTypeUnsupported
    case 20: self = .credentialsMissing
    case 21: self = .resourceProjectInvalid
    case 23: self = .sessionCookieInvalid
    case 24: self = .userBlockedByAdmin
    case 25: self = .resourceUsageRestrictionViolated
    case 26: self = .systemParameterUnsupported
    case 27: self = .orgRestrictionViolation
    case 28: self = .orgRestrictionHeaderInvalid
    case 29: self = .serviceNotVisible
    case 30: self = .gcpSuspended
    case 31: self = .locationPolicyViolated
    case 33: self = .missingOrigin
    case 34: self = .overloadedCredentials
    case 35: self = .locationOrgPolicyViolated
    case 36: self = .tlsOrgPolicyViolated
    case 38: self = .emulatorQuotaExceeded
    case 39: self = .credentialAndroidAppInvalid
    case 41: self = .iamPermissionDenied
    case 42: self = .jwtTokenInvalid
    case 43: self = .credentialTypeUnsupported
    case 44: self = .accountTypeUnsupported
    case 45: self = .endpointUsageRestrictionViolated
    case 46: self = .tlsCipherRestrictionViolated
    case 47: self = .mcpServerDisabled
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .serviceDisabled: return try container.encode(1)
    case .billingDisabled: return try container.encode(2)
    case .apiKeyInvalid: return try container.encode(3)
    case .apiKeyServiceBlocked: return try container.encode(4)
    case .rateLimitExceeded: return try container.encode(5)
    case .resourceQuotaExceeded: return try container.encode(6)
    case .apiKeyHttpReferrerBlocked: return try container.encode(7)
    case .apiKeyIpAddressBlocked: return try container.encode(8)
    case .apiKeyAndroidAppBlocked: return try container.encode(9)
    case .locationTaxPolicyViolated: return try container.encode(10)
    case .userProjectDenied: return try container.encode(11)
    case .consumerSuspended: return try container.encode(12)
    case .apiKeyIosAppBlocked: return try container.encode(13)
    case .consumerInvalid: return try container.encode(14)
    case .securityPolicyViolated: return try container.encode(15)
    case .accessTokenExpired: return try container.encode(16)
    case .accessTokenScopeInsufficient: return try container.encode(17)
    case .accountStateInvalid: return try container.encode(18)
    case .accessTokenTypeUnsupported: return try container.encode(19)
    case .credentialsMissing: return try container.encode(20)
    case .resourceProjectInvalid: return try container.encode(21)
    case .sessionCookieInvalid: return try container.encode(23)
    case .userBlockedByAdmin: return try container.encode(24)
    case .resourceUsageRestrictionViolated: return try container.encode(25)
    case .systemParameterUnsupported: return try container.encode(26)
    case .orgRestrictionViolation: return try container.encode(27)
    case .orgRestrictionHeaderInvalid: return try container.encode(28)
    case .serviceNotVisible: return try container.encode(29)
    case .gcpSuspended: return try container.encode(30)
    case .locationPolicyViolated: return try container.encode(31)
    case .missingOrigin: return try container.encode(33)
    case .overloadedCredentials: return try container.encode(34)
    case .locationOrgPolicyViolated: return try container.encode(35)
    case .tlsOrgPolicyViolated: return try container.encode(36)
    case .emulatorQuotaExceeded: return try container.encode(38)
    case .credentialAndroidAppInvalid: return try container.encode(39)
    case .iamPermissionDenied: return try container.encode(41)
    case .jwtTokenInvalid: return try container.encode(42)
    case .credentialTypeUnsupported: return try container.encode(43)
    case .accountTypeUnsupported: return try container.encode(44)
    case .endpointUsageRestrictionViolated: return try container.encode(45)
    case .tlsCipherRestrictionViolated: return try container.encode(46)
    case .mcpServerDisabled: return try container.encode(47)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
