// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// An indicator of the behavior of a given field (for example, that a field
/// is required in requests, or given as output but ignored as input).
/// This **does not** change the behavior in protocol buffers itself; it only
/// denotes the behavior and may affect how API tooling handles the field.
///
/// Note: This enum **may** receive new values in the future.
public enum FieldBehavior: Codable, Equatable, Sendable {
  case unspecified
  case `optional`
  case `required`
  case outputOnly
  case inputOnly
  case immutable
  case unorderedList
  case nonEmptyDefault
  case identifier
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .`optional`: return 1
    case .`required`: return 2
    case .outputOnly: return 3
    case .inputOnly: return 4
    case .immutable: return 5
    case .unorderedList: return 6
    case .nonEmptyDefault: return 7
    case .identifier: return 8
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: String? {
    switch self {
    case .unspecified: return "FIELD_BEHAVIOR_UNSPECIFIED"
    case .`optional`: return "OPTIONAL"
    case .`required`: return "REQUIRED"
    case .outputOnly: return "OUTPUT_ONLY"
    case .inputOnly: return "INPUT_ONLY"
    case .immutable: return "IMMUTABLE"
    case .unorderedList: return "UNORDERED_LIST"
    case .nonEmptyDefault: return "NON_EMPTY_DEFAULT"
    case .identifier: return "IDENTIFIER"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: String) {
    switch stringValue {
    case "FIELD_BEHAVIOR_UNSPECIFIED": self = .unspecified
    case "OPTIONAL": self = .`optional`
    case "REQUIRED": self = .`required`
    case "OUTPUT_ONLY": self = .outputOnly
    case "INPUT_ONLY": self = .inputOnly
    case "IMMUTABLE": self = .immutable
    case "UNORDERED_LIST": self = .unorderedList
    case "NON_EMPTY_DEFAULT": self = .nonEmptyDefault
    case "IDENTIFIER": self = .identifier
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .`optional`
    case 2: self = .`required`
    case 3: self = .outputOnly
    case 4: self = .inputOnly
    case 5: self = .immutable
    case 6: self = .unorderedList
    case 7: self = .nonEmptyDefault
    case 8: self = .identifier
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .`optional`: return try container.encode(1)
    case .`required`: return try container.encode(2)
    case .outputOnly: return try container.encode(3)
    case .inputOnly: return try container.encode(4)
    case .immutable: return try container.encode(5)
    case .unorderedList: return try container.encode(6)
    case .nonEmptyDefault: return try container.encode(7)
    case .identifier: return try container.encode(8)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
