// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The launch stage as defined by [Google Cloud Platform
/// Launch Stages](https://cloud.google.com/terms/launch-stages).
public enum LaunchStage: Codable, Equatable, Sendable {
  case unspecified
  case earlyAccess
  case alpha
  case beta
  case ga
  case deprecated
  case unimplemented
  case prelaunch
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .earlyAccess: return 1
    case .alpha: return 2
    case .beta: return 3
    case .ga: return 4
    case .deprecated: return 5
    case .unimplemented: return 6
    case .prelaunch: return 7
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: String? {
    switch self {
    case .unspecified: return "LAUNCH_STAGE_UNSPECIFIED"
    case .earlyAccess: return "EARLY_ACCESS"
    case .alpha: return "ALPHA"
    case .beta: return "BETA"
    case .ga: return "GA"
    case .deprecated: return "DEPRECATED"
    case .unimplemented: return "UNIMPLEMENTED"
    case .prelaunch: return "PRELAUNCH"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: String) {
    switch stringValue {
    case "LAUNCH_STAGE_UNSPECIFIED": self = .unspecified
    case "UNIMPLEMENTED": self = .unimplemented
    case "PRELAUNCH": self = .prelaunch
    case "EARLY_ACCESS": self = .earlyAccess
    case "ALPHA": self = .alpha
    case "BETA": self = .beta
    case "GA": self = .ga
    case "DEPRECATED": self = .deprecated
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 6: self = .unimplemented
    case 7: self = .prelaunch
    case 1: self = .earlyAccess
    case 2: self = .alpha
    case 3: self = .beta
    case 4: self = .ga
    case 5: self = .deprecated
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .earlyAccess: return try container.encode(1)
    case .alpha: return try container.encode(2)
    case .beta: return try container.encode(3)
    case .ga: return try container.encode(4)
    case .deprecated: return try container.encode(5)
    case .unimplemented: return try container.encode(6)
    case .prelaunch: return try container.encode(7)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
