// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Describes the generator configuration for a method.
public struct MethodSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The fully qualified name of the method, for which the options below apply.
  /// This is used to find the method to apply the options.
  ///
  /// Example:
  ///
  ///    publishing:
  ///      method_settings:
  ///      - selector: google.storage.control.v2.StorageControl.CreateFolder
  ///        # method settings for CreateFolder...
  public var selector: Swift.String

  /// Describes settings to use for long-running operations when generating
  /// API methods for RPCs. Complements RPCs that use the annotations in
  /// google/longrunning/operations.proto.
  ///
  /// Example of a YAML configuration::
  ///
  ///    publishing:
  ///      method_settings:
  ///      - selector: google.cloud.speech.v2.Speech.BatchRecognize
  ///        long_running:
  ///          initial_poll_delay: 60s # 1 minute
  ///          poll_delay_multiplier: 1.5
  ///          max_poll_delay: 360s # 6 minutes
  ///          total_poll_timeout: 54000s # 90 minutes
  public var longRunning: MethodSettings.LongRunning?

  /// List of top-level fields of the request message, that should be
  /// automatically populated by the client libraries based on their
  /// (google.api.field_info).format. Currently supported format: UUID4.
  ///
  /// Example of a YAML configuration:
  ///
  ///    publishing:
  ///      method_settings:
  ///      - selector: google.example.v1.ExampleService.CreateExample
  ///        auto_populated_fields:
  ///        - request_id
  public var autoPopulatedFields: [Swift.String]

  /// Initialize a new instance of `MethodSettings`.
  public init(
    selector: Swift.String = Swift.String(),
    longRunning: MethodSettings.LongRunning? = nil,
    autoPopulatedFields: [Swift.String] = [],
  ) {
    self.selector = selector
    self.longRunning = longRunning
    self.autoPopulatedFields = autoPopulatedFields
  }

  /// Describes settings to use when generating API methods that use the
  /// long-running operation pattern.
  /// All default values below are from those used in the client library
  /// generators (e.g.
  /// [Java](https://github.com/googleapis/gapic-generator-java/blob/04c2faa191a9b5a10b92392fe8482279c4404803/src/main/java/com/google/api/generator/gapic/composer/common/RetrySettingsComposer.java)).
  public struct LongRunning: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initial delay after which the first poll request will be made.
    /// Default value: 5 seconds.
    public var initialPollDelay: GoogleCloudWkt.Duration?

    /// Multiplier to gradually increase delay between subsequent polls until it
    /// reaches max_poll_delay.
    /// Default value: 1.5.
    public var pollDelayMultiplier: Swift.Float

    /// Maximum time between two subsequent poll requests.
    /// Default value: 45 seconds.
    public var maxPollDelay: GoogleCloudWkt.Duration?

    /// Total polling timeout.
    /// Default value: 5 minutes.
    public var totalPollTimeout: GoogleCloudWkt.Duration?

    /// Initialize a new instance of `LongRunning`.
    public init(
      initialPollDelay: GoogleCloudWkt.Duration? = nil,
      pollDelayMultiplier: Swift.Float = Swift.Float(),
      maxPollDelay: GoogleCloudWkt.Duration? = nil,
      totalPollTimeout: GoogleCloudWkt.Duration? = nil,
    ) {
      self.initialPollDelay = initialPollDelay
      self.pollDelayMultiplier = pollDelayMultiplier
      self.maxPollDelay = maxPollDelay
      self.totalPollTimeout = totalPollTimeout
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.api.MethodSettings.LongRunning"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.api.MethodSettings" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
