// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Defines a metric type and its schema. Once a metric descriptor is created,
/// deleting or altering it stops data collection and makes the metric type's
/// existing data unusable.
///
public struct MetricDescriptor: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The resource name of the metric descriptor.
  public var name: Swift.String = Swift.String()

  /// The metric type, including its DNS name prefix. The type is not
  /// URL-encoded. All user-defined metric types have the DNS name
  /// `custom.googleapis.com` or `external.googleapis.com`. Metric types should
  /// use a natural hierarchical grouping. For example:
  ///
  ///     "custom.googleapis.com/invoice/paid/amount"
  ///     "external.googleapis.com/prometheus/up"
  ///     "appengine.googleapis.com/http/server/response_latencies"
  public var type: Swift.String = Swift.String()

  /// The set of labels that can be used to describe a specific
  /// instance of this metric type. For example, the
  /// `appengine.googleapis.com/http/server/response_latencies` metric
  /// type has a label for the HTTP response code, `response_code`, so
  /// you can look at latencies for successful responses or just
  /// for responses that failed.
  public var labels: [LabelDescriptor] = []

  /// Whether the metric records instantaneous values, changes to a value, etc.
  /// Some combinations of `metric_kind` and `value_type` might not be supported.
  public var metricKind: MetricDescriptor.MetricKind = MetricDescriptor.MetricKind()

  /// Whether the measurement is an integer, a floating-point number, etc.
  /// Some combinations of `metric_kind` and `value_type` might not be supported.
  public var valueType: MetricDescriptor.ValueType = MetricDescriptor.ValueType()

  /// The units in which the metric value is reported. It is only applicable
  /// if the `value_type` is `INT64`, `DOUBLE`, or `DISTRIBUTION`. The `unit`
  /// defines the representation of the stored metric values.
  ///
  /// Different systems might scale the values to be more easily displayed (so a
  /// value of `0.02kBy` _might_ be displayed as `20By`, and a value of
  /// `3523kBy` _might_ be displayed as `3.5MBy`). However, if the `unit` is
  /// `kBy`, then the value of the metric is always in thousands of bytes, no
  /// matter how it might be displayed.
  ///
  /// If you want a custom metric to record the exact number of CPU-seconds used
  /// by a job, you can create an `INT64 CUMULATIVE` metric whose `unit` is
  /// `s{CPU}` (or equivalently `1s{CPU}` or just `s`). If the job uses 12,005
  /// CPU-seconds, then the value is written as `12005`.
  ///
  /// Alternatively, if you want a custom metric to record data in a more
  /// granular way, you can create a `DOUBLE CUMULATIVE` metric whose `unit` is
  /// `ks{CPU}`, and then write the value `12.005` (which is `12005/1000`),
  /// or use `Kis{CPU}` and write `11.723` (which is `12005/1024`).
  ///
  /// The supported units are a subset of [The Unified Code for Units of
  /// Measure](https://unitsofmeasure.org/ucum.html) standard:
  ///
  /// **Basic units (UNIT)**
  ///
  /// * `bit`   bit
  /// * `By`    byte
  /// * `s`     second
  /// * `min`   minute
  /// * `h`     hour
  /// * `d`     day
  /// * `1`     dimensionless
  ///
  /// **Prefixes (PREFIX)**
  ///
  /// * `k`     kilo    (10^3)
  /// * `M`     mega    (10^6)
  /// * `G`     giga    (10^9)
  /// * `T`     tera    (10^12)
  /// * `P`     peta    (10^15)
  /// * `E`     exa     (10^18)
  /// * `Z`     zetta   (10^21)
  /// * `Y`     yotta   (10^24)
  ///
  /// * `m`     milli   (10^-3)
  /// * `u`     micro   (10^-6)
  /// * `n`     nano    (10^-9)
  /// * `p`     pico    (10^-12)
  /// * `f`     femto   (10^-15)
  /// * `a`     atto    (10^-18)
  /// * `z`     zepto   (10^-21)
  /// * `y`     yocto   (10^-24)
  ///
  /// * `Ki`    kibi    (2^10)
  /// * `Mi`    mebi    (2^20)
  /// * `Gi`    gibi    (2^30)
  /// * `Ti`    tebi    (2^40)
  /// * `Pi`    pebi    (2^50)
  ///
  /// **Grammar**
  ///
  /// The grammar also includes these connectors:
  ///
  /// * `/`    division or ratio (as an infix operator). For examples,
  ///          `kBy/{email}` or `MiBy/10ms` (although you should almost never
  ///          have `/s` in a metric `unit`; rates should always be computed at
  ///          query time from the underlying cumulative or delta value).
  /// * `.`    multiplication or composition (as an infix operator). For
  ///          examples, `GBy.d` or `k{watt}.h`.
  ///
  /// The grammar for a unit is as follows:
  ///
  ///     Expression = Component { "." Component } { "/" Component } ;
  ///
  ///     Component = ( [ PREFIX ] UNIT | "%" ) [ Annotation ]
  ///               | Annotation
  ///               | "1"
  ///               ;
  ///
  ///     Annotation = "{" NAME "}" ;
  ///
  /// Notes:
  ///
  /// * `Annotation` is just a comment if it follows a `UNIT`. If the annotation
  ///    is used alone, then the unit is equivalent to `1`. For examples,
  ///    `{request}/s == 1/s`, `By{transmitted}/s == By/s`.
  /// * `NAME` is a sequence of non-blank printable ASCII characters not
  ///    containing `{` or `}`.
  /// * `1` represents a unitary [dimensionless
  ///    unit](https://en.wikipedia.org/wiki/Dimensionless_quantity) of 1, such
  ///    as in `1/s`. It is typically used when none of the basic units are
  ///    appropriate. For example, "new users per day" can be represented as
  ///    `1/d` or `{new-users}/d` (and a metric value `5` would mean "5 new
  ///    users). Alternatively, "thousands of page views per day" would be
  ///    represented as `1000/d` or `k1/d` or `k{page_views}/d` (and a metric
  ///    value of `5.3` would mean "5300 page views per day").
  /// * `%` represents dimensionless value of 1/100, and annotates values giving
  ///    a percentage (so the metric values are typically in the range of 0..100,
  ///    and a metric value `3` means "3 percent").
  /// * `10^2.%` indicates a metric contains a ratio, typically in the range
  ///    0..1, that will be multiplied by 100 and displayed as a percentage
  ///    (so a metric value `0.03` means "3 percent").
  public var unit: Swift.String = Swift.String()

  /// A detailed description of the metric, which can be used in documentation.
  public var description: Swift.String = Swift.String()

  /// A concise name for the metric, which can be displayed in user interfaces.
  /// Use sentence case without an ending period, for example "Request count".
  /// This field is optional but it is recommended to be set for any metrics
  /// associated with user-visible concepts, such as Quota.
  public var displayName: Swift.String = Swift.String()

  /// Optional. Metadata which can be used to guide usage of the metric.
  public var metadata: MetricDescriptor.MetricDescriptorMetadata? = nil

  /// Optional. The launch stage of the metric definition.
  public var launchStage: LaunchStage = LaunchStage()

  /// Read-only. If present, then a [time
  /// series][google.monitoring.v3.TimeSeries], which is identified partially by
  /// a metric type and a
  /// [MonitoredResourceDescriptor][google.api.MonitoredResourceDescriptor], that
  /// is associated with this metric type can only be associated with one of the
  /// monitored resource types listed here.
  ///
  /// [google.api.MonitoredResourceDescriptor]: <doc:MonitoredResourceDescriptor>
  public var monitoredResourceTypes: [Swift.String] = []

  /// Initialize a new instance of `MetricDescriptor`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MetricDescriptor().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Additional annotations that can be used to guide the usage of a metric.
  public struct MetricDescriptorMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Deprecated. Must use the
    /// [MetricDescriptor.launch_stage][google.api.MetricDescriptor.launch_stage]
    /// instead.
    ///
    /// [google.api.MetricDescriptor.launch_stage]: <doc:MetricDescriptor/launchStage>
    @available(*, deprecated)
    public var launchStage: LaunchStage = LaunchStage()

    /// The sampling period of metric data points. For metrics which are written
    /// periodically, consecutive data points are stored at this time interval,
    /// excluding data loss due to errors. Metrics with a higher granularity have
    /// a smaller sampling period.
    public var samplePeriod: GoogleCloudWKT.Duration? = nil

    /// The delay of data points caused by ingestion. Data points older than this
    /// age are guaranteed to be ingested and available to be read, excluding
    /// data loss due to errors.
    public var ingestDelay: GoogleCloudWKT.Duration? = nil

    /// The scope of the timeseries data of the metric.
    public var timeSeriesResourceHierarchyLevel:
      [MetricDescriptor.MetricDescriptorMetadata.TimeSeriesResourceHierarchyLevel] = []

    /// Initialize a new instance of `MetricDescriptorMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MetricDescriptorMetadata().with { $0.launchStage = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The resource hierarchy level of the timeseries data of a metric.
    public enum TimeSeriesResourceHierarchyLevel: Codable, Equatable, Sendable {
      /// Do not use this default value.
      case unspecified
      /// Scopes a metric to a project.
      case project
      /// Scopes a metric to an organization.
      case organization
      /// Scopes a metric to a folder.
      case folder
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .project: return 1
        case .organization: return 2
        case .folder: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "TIME_SERIES_RESOURCE_HIERARCHY_LEVEL_UNSPECIFIED"
        case .project: return "PROJECT"
        case .organization: return "ORGANIZATION"
        case .folder: return "FOLDER"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TimeSeriesResourceHierarchyLevel/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TIME_SERIES_RESOURCE_HIERARCHY_LEVEL_UNSPECIFIED": self = .unspecified
        case "PROJECT": self = .project
        case "ORGANIZATION": self = .organization
        case "FOLDER": self = .folder
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TimeSeriesResourceHierarchyLevel/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .project
        case 2: self = .organization
        case 3: self = .folder
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .project: return try container.encode(1)
        case .organization: return try container.encode(2)
        case .folder: return try container.encode(3)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.MetricDescriptor.MetricDescriptorMetadata"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The kind of measurement. It describes how the data is reported.
  /// For information on setting the start time and end time based on
  /// the MetricKind, see [TimeInterval][google.monitoring.v3.TimeInterval].
  public enum MetricKind: Codable, Equatable, Sendable {
    /// Do not use this default value.
    case unspecified
    /// An instantaneous measurement of a value.
    case gauge
    /// The change in a value during a time interval.
    case delta
    /// A value accumulated over a time interval.  Cumulative
    /// measurements in a time series should have the same start time
    /// and increasing end times, until an event resets the cumulative
    /// value to zero and sets a new start time for the following
    /// points.
    case cumulative
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .gauge: return 1
      case .delta: return 2
      case .cumulative: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "METRIC_KIND_UNSPECIFIED"
      case .gauge: return "GAUGE"
      case .delta: return "DELTA"
      case .cumulative: return "CUMULATIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MetricKind/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "METRIC_KIND_UNSPECIFIED": self = .unspecified
      case "GAUGE": self = .gauge
      case "DELTA": self = .delta
      case "CUMULATIVE": self = .cumulative
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MetricKind/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .gauge
      case 2: self = .delta
      case 3: self = .cumulative
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .gauge: return try container.encode(1)
      case .delta: return try container.encode(2)
      case .cumulative: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The value type of a metric.
  public enum ValueType: Codable, Equatable, Sendable {
    /// Do not use this default value.
    case unspecified
    /// The value is a boolean.
    /// This value type can be used only if the metric kind is `GAUGE`.
    case bool
    /// The value is a signed 64-bit integer.
    case int64
    /// The value is a double precision floating point number.
    case double
    /// The value is a text string.
    /// This value type can be used only if the metric kind is `GAUGE`.
    case string
    /// The value is a [`Distribution`][google.api.Distribution].
    ///
    /// [google.api.Distribution]: <doc:Distribution>
    case distribution
    /// The value is money.
    case money
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .bool: return 1
      case .int64: return 2
      case .double: return 3
      case .string: return 4
      case .distribution: return 5
      case .money: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VALUE_TYPE_UNSPECIFIED"
      case .bool: return "BOOL"
      case .int64: return "INT64"
      case .double: return "DOUBLE"
      case .string: return "STRING"
      case .distribution: return "DISTRIBUTION"
      case .money: return "MONEY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ValueType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VALUE_TYPE_UNSPECIFIED": self = .unspecified
      case "BOOL": self = .bool
      case "INT64": self = .int64
      case "DOUBLE": self = .double
      case "STRING": self = .string
      case "DISTRIBUTION": self = .distribution
      case "MONEY": self = .money
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ValueType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .bool
      case 2: self = .int64
      case 3: self = .double
      case 4: self = .string
      case 5: self = .distribution
      case 6: self = .money
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .bool: return try container.encode(1)
      case .int64: return try container.encode(2)
      case .double: return try container.encode(3)
      case .string: return try container.encode(4)
      case .distribution: return try container.encode(5)
      case .money: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.MetricDescriptor"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
