// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An object representing a resource that can be used for monitoring, logging,
/// billing, or other purposes. Examples include virtual machine instances,
/// databases, and storage devices such as disks. The `type` field identifies a
/// [MonitoredResourceDescriptor][google.api.MonitoredResourceDescriptor] object
/// that describes the resource's schema. Information in the `labels` field
/// identifies the actual resource and its attributes according to the schema.
/// For example, a particular Compute Engine VM instance could be represented by
/// the following object, because the
/// [MonitoredResourceDescriptor][google.api.MonitoredResourceDescriptor] for
/// `"gce_instance"` has labels
/// `"project_id"`, `"instance_id"` and `"zone"`:
///
///     { "type": "gce_instance",
///       "labels": { "project_id": "my-project",
///                   "instance_id": "12345678901234",
///                   "zone": "us-central1-a" }}
///
/// [google.api.MonitoredResourceDescriptor]: <doc:MonitoredResourceDescriptor>
public struct MonitoredResource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The monitored resource type. This field must match
  /// the `type` field of a
  /// [MonitoredResourceDescriptor][google.api.MonitoredResourceDescriptor]
  /// object. For example, the type of a Compute Engine VM instance is
  /// `gce_instance`. Some descriptors include the service name in the type; for
  /// example, the type of a Datastream stream is
  /// `datastream.googleapis.com/Stream`.
  ///
  /// [google.api.MonitoredResourceDescriptor]: <doc:MonitoredResourceDescriptor>
  public var type: Swift.String

  /// Required. Values for all of the labels listed in the associated monitored
  /// resource descriptor. For example, Compute Engine VM instances use the
  /// labels `"project_id"`, `"instance_id"`, and `"zone"`.
  public var labels: [Swift.String: Swift.String]

  /// Initialize a new instance of `MonitoredResource`.
  public init(
    type: Swift.String = Swift.String(),
    labels: [Swift.String: Swift.String] = [:],
  ) {
    self.type = type
    self.labels = labels
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.api.MonitoredResource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
