// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Settings for Php client libraries.
public struct PhpSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Some settings.
  public var common: CommonLanguageSettings? = nil

  /// The package name to use in Php. Clobbers the php_namespace option
  /// set in the protobuf. This should be used **only** by APIs
  /// who have already set the language_settings.php.package_name" field
  /// in gapic.yaml. API teams should use the protobuf php_namespace option
  /// where possible.
  ///
  /// Example of a YAML configuration::
  ///
  ///     publishing:
  ///       library_settings:
  ///         php_settings:
  ///           library_package: Google\Cloud\PubSub\V1
  public var libraryPackage: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PhpSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PhpSettings().with { $0.common = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let common = CodingKeys(stringValue: "common")
    static let libraryPackage = CodingKeys(stringValue: "libraryPackage")

    static let _knownKeys: Set<Swift.String> = [
      "common",
      "libraryPackage",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.common = try container.decodeIfPresent(CommonLanguageSettings.self, forKey: .common)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .libraryPackage) {
      self.libraryPackage = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.common, forKey: .common)
    try container.encode(self.libraryPackage, forKey: .libraryPackage)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.PhpSettings"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
