// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// This message configures the settings for publishing [Google Cloud Client
/// libraries](https://cloud.google.com/apis/docs/cloud-client-libraries)
/// generated from the service config.
public struct Publishing: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A list of API method settings, e.g. the behavior for methods that use the
  /// long-running operation pattern.
  public var methodSettings: [MethodSettings] = []

  /// Link to a *public* URI where users can report issues.  Example:
  /// https://issuetracker.google.com/issues/new?component=190865&template=1161103
  public var newIssueUri: Swift.String = Swift.String()

  /// Link to product home page.  Example:
  /// https://cloud.google.com/asset-inventory/docs/overview
  public var documentationUri: Swift.String = Swift.String()

  /// Used as a tracking tag when collecting data about the APIs developer
  /// relations artifacts like docs, packages delivered to package managers,
  /// etc.  Example: "speech".
  public var apiShortName: Swift.String = Swift.String()

  /// GitHub label to apply to issues and pull requests opened for this API.
  public var githubLabel: Swift.String = Swift.String()

  /// GitHub teams to be added to CODEOWNERS in the directory in GitHub
  /// containing source code for the client libraries for this API.
  public var codeownerGithubTeams: [Swift.String] = []

  /// A prefix used in sample code when demarking regions to be included in
  /// documentation.
  public var docTagPrefix: Swift.String = Swift.String()

  /// For whom the client library is being published.
  public var organization: ClientLibraryOrganization = ClientLibraryOrganization()

  /// Client library settings.  If the same version string appears multiple
  /// times in this list, then the last one wins.  Settings from earlier
  /// settings with the same version string are discarded.
  public var librarySettings: [ClientLibrarySettings] = []

  /// Optional link to proto reference documentation.  Example:
  /// https://cloud.google.com/pubsub/lite/docs/reference/rpc
  public var protoReferenceDocumentationUri: Swift.String = Swift.String()

  /// Optional link to REST reference documentation.  Example:
  /// https://cloud.google.com/pubsub/lite/docs/reference/rest
  public var restReferenceDocumentationUri: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Publishing`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Publishing().with { $0.methodSettings = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let methodSettings = CodingKeys(stringValue: "methodSettings")
    static let newIssueUri = CodingKeys(stringValue: "newIssueUri")
    static let documentationUri = CodingKeys(stringValue: "documentationUri")
    static let apiShortName = CodingKeys(stringValue: "apiShortName")
    static let githubLabel = CodingKeys(stringValue: "githubLabel")
    static let codeownerGithubTeams = CodingKeys(stringValue: "codeownerGithubTeams")
    static let docTagPrefix = CodingKeys(stringValue: "docTagPrefix")
    static let organization = CodingKeys(stringValue: "organization")
    static let librarySettings = CodingKeys(stringValue: "librarySettings")
    static let protoReferenceDocumentationUri = CodingKeys(
      stringValue: "protoReferenceDocumentationUri")
    static let restReferenceDocumentationUri = CodingKeys(
      stringValue: "restReferenceDocumentationUri")

    static let _knownKeys: Set<Swift.String> = [
      "methodSettings",
      "newIssueUri",
      "documentationUri",
      "apiShortName",
      "githubLabel",
      "codeownerGithubTeams",
      "docTagPrefix",
      "organization",
      "librarySettings",
      "protoReferenceDocumentationUri",
      "restReferenceDocumentationUri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([MethodSettings].self, forKey: .methodSettings) {
      self.methodSettings = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .newIssueUri) {
      self.newIssueUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .documentationUri) {
      self.documentationUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .apiShortName) {
      self.apiShortName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .githubLabel) {
      self.githubLabel = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .codeownerGithubTeams)
    {
      self.codeownerGithubTeams = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .docTagPrefix) {
      self.docTagPrefix = value
    }
    if let value = try container.decodeIfPresent(
      ClientLibraryOrganization.self, forKey: .organization)
    {
      self.organization = value
    }
    if let value = try container.decodeIfPresent(
      [ClientLibrarySettings].self, forKey: .librarySettings)
    {
      self.librarySettings = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .protoReferenceDocumentationUri)
    {
      self.protoReferenceDocumentationUri = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .restReferenceDocumentationUri)
    {
      self.restReferenceDocumentationUri = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.methodSettings, forKey: .methodSettings)
    try container.encode(self.newIssueUri, forKey: .newIssueUri)
    try container.encode(self.documentationUri, forKey: .documentationUri)
    try container.encode(self.apiShortName, forKey: .apiShortName)
    try container.encode(self.githubLabel, forKey: .githubLabel)
    try container.encode(self.codeownerGithubTeams, forKey: .codeownerGithubTeams)
    try container.encode(self.docTagPrefix, forKey: .docTagPrefix)
    try container.encode(self.organization, forKey: .organization)
    try container.encode(self.librarySettings, forKey: .librarySettings)
    try container.encode(
      self.protoReferenceDocumentationUri, forKey: .protoReferenceDocumentationUri)
    try container.encode(self.restReferenceDocumentationUri, forKey: .restReferenceDocumentationUri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.Publishing"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
