// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Settings for Python client libraries.
public struct PythonSettings: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Some settings.
  public var common: CommonLanguageSettings? = nil

  /// Experimental features to be included during client library generation.
  public var experimentalFeatures: PythonSettings.ExperimentalFeatures? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `PythonSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PythonSettings().with { $0.common = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let common = CodingKeys(stringValue: "common")
    static let experimentalFeatures = CodingKeys(stringValue: "experimentalFeatures")

    static let _knownKeys: Set<Swift.String> = [
      "common",
      "experimentalFeatures",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.common = try container.decodeIfPresent(CommonLanguageSettings.self, forKey: .common)
    self.experimentalFeatures = try container.decodeIfPresent(
      PythonSettings.ExperimentalFeatures.self, forKey: .experimentalFeatures)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.common, forKey: .common)
    try container.encodeIfPresent(self.experimentalFeatures, forKey: .experimentalFeatures)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Experimental features to be included during client library generation.
  /// These fields will be deprecated once the feature graduates and is enabled
  /// by default.
  public struct ExperimentalFeatures: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Enables generation of asynchronous REST clients if `rest` transport is
    /// enabled. By default, asynchronous REST clients will not be generated.
    /// This feature will be enabled by default 1 month after launching the
    /// feature in preview packages.
    public var restAsyncIoEnabled: Swift.Bool = Swift.Bool()

    /// Enables generation of protobuf code using new types that are more
    /// Pythonic which are included in `protobuf>=5.29.x`. This feature will be
    /// enabled by default 1 month after launching the feature in preview
    /// packages.
    public var protobufPythonicTypesEnabled: Swift.Bool = Swift.Bool()

    /// Disables generation of an unversioned Python package for this client
    /// library. This means that the module names will need to be versioned in
    /// import statements. For example `import google.cloud.library_v2` instead
    /// of `import google.cloud.library`.
    public var unversionedPackageDisabled: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `ExperimentalFeatures`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ExperimentalFeatures().with { $0.restAsyncIoEnabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let restAsyncIoEnabled = CodingKeys(stringValue: "restAsyncIoEnabled")
      static let protobufPythonicTypesEnabled = CodingKeys(
        stringValue: "protobufPythonicTypesEnabled")
      static let unversionedPackageDisabled = CodingKeys(stringValue: "unversionedPackageDisabled")

      static let _knownKeys: Set<Swift.String> = [
        "restAsyncIoEnabled",
        "protobufPythonicTypesEnabled",
        "unversionedPackageDisabled",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .restAsyncIoEnabled) {
        self.restAsyncIoEnabled = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .protobufPythonicTypesEnabled)
      {
        self.protobufPythonicTypesEnabled = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .unversionedPackageDisabled)
      {
        self.unversionedPackageDisabled = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.restAsyncIoEnabled, forKey: .restAsyncIoEnabled)
      try container.encode(self.protobufPythonicTypesEnabled, forKey: .protobufPythonicTypesEnabled)
      try container.encode(self.unversionedPackageDisabled, forKey: .unversionedPackageDisabled)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.PythonSettings.ExperimentalFeatures"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.PythonSettings"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
