// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Settings for Python client libraries.
public struct PythonSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Some settings.
  public var common: CommonLanguageSettings?

  /// Experimental features to be included during client library generation.
  public var experimentalFeatures: PythonSettings.ExperimentalFeatures?

  /// Initialize a new instance of `PythonSettings`.
  public init(
    common: CommonLanguageSettings? = nil,
    experimentalFeatures: PythonSettings.ExperimentalFeatures? = nil,
  ) {
    self.common = common
    self.experimentalFeatures = experimentalFeatures
  }

  /// Experimental features to be included during client library generation.
  /// These fields will be deprecated once the feature graduates and is enabled
  /// by default.
  public struct ExperimentalFeatures: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Enables generation of asynchronous REST clients if `rest` transport is
    /// enabled. By default, asynchronous REST clients will not be generated.
    /// This feature will be enabled by default 1 month after launching the
    /// feature in preview packages.
    public var restAsyncIoEnabled: Swift.Bool

    /// Enables generation of protobuf code using new types that are more
    /// Pythonic which are included in `protobuf>=5.29.x`. This feature will be
    /// enabled by default 1 month after launching the feature in preview
    /// packages.
    public var protobufPythonicTypesEnabled: Swift.Bool

    /// Disables generation of an unversioned Python package for this client
    /// library. This means that the module names will need to be versioned in
    /// import statements. For example `import google.cloud.library_v2` instead
    /// of `import google.cloud.library`.
    public var unversionedPackageDisabled: Swift.Bool

    /// Initialize a new instance of `ExperimentalFeatures`.
    public init(
      restAsyncIoEnabled: Swift.Bool = Swift.Bool(),
      protobufPythonicTypesEnabled: Swift.Bool = Swift.Bool(),
      unversionedPackageDisabled: Swift.Bool = Swift.Bool(),
    ) {
      self.restAsyncIoEnabled = restAsyncIoEnabled
      self.protobufPythonicTypesEnabled = protobufPythonicTypesEnabled
      self.unversionedPackageDisabled = unversionedPackageDisabled
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.api.PythonSettings.ExperimentalFeatures"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.api.PythonSettings" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
