// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Settings for Python client libraries.
public struct PythonSettings: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Some settings.
  public var common: CommonLanguageSettings? = nil

  /// Experimental features to be included during client library generation.
  public var experimentalFeatures: PythonSettings.ExperimentalFeatures? = nil

  /// Initialize a new instance of `PythonSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PythonSettings().with { $0.common = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Experimental features to be included during client library generation.
  /// These fields will be deprecated once the feature graduates and is enabled
  /// by default.
  public struct ExperimentalFeatures: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Enables generation of asynchronous REST clients if `rest` transport is
    /// enabled. By default, asynchronous REST clients will not be generated.
    /// This feature will be enabled by default 1 month after launching the
    /// feature in preview packages.
    public var restAsyncIoEnabled: Swift.Bool = Swift.Bool()

    /// Enables generation of protobuf code using new types that are more
    /// Pythonic which are included in `protobuf>=5.29.x`. This feature will be
    /// enabled by default 1 month after launching the feature in preview
    /// packages.
    public var protobufPythonicTypesEnabled: Swift.Bool = Swift.Bool()

    /// Disables generation of an unversioned Python package for this client
    /// library. This means that the module names will need to be versioned in
    /// import statements. For example `import google.cloud.library_v2` instead
    /// of `import google.cloud.library`.
    public var unversionedPackageDisabled: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `ExperimentalFeatures`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ExperimentalFeatures().with { $0.restAsyncIoEnabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.PythonSettings.ExperimentalFeatures"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.PythonSettings"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
