// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// `QuotaLimit` defines a specific limit that applies over a specified duration
/// for a limit type. There can be at most one limit for a duration and limit
/// type combination defined within a `QuotaGroup`.
public struct QuotaLimit: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of the quota limit.
  ///
  /// The name must be provided, and it must be unique within the service. The
  /// name can only include alphanumeric characters as well as '-'.
  ///
  /// The maximum length of the limit name is 64 characters.
  public var name: Swift.String = Swift.String()

  /// Optional. User-visible, extended description for this quota limit.
  /// Should be used only when more context is needed to understand this limit
  /// than provided by the limit's display name (see: `display_name`).
  public var description: Swift.String = Swift.String()

  /// Default number of tokens that can be consumed during the specified
  /// duration. This is the number of tokens assigned when a client
  /// application developer activates the service for his/her project.
  ///
  /// Specifying a value of 0 will block all requests. This can be used if you
  /// are provisioning quota to selected consumers and blocking others.
  /// Similarly, a value of -1 will indicate an unlimited quota. No other
  /// negative values are allowed.
  ///
  /// Used by group-based quotas only.
  public var defaultLimit: Swift.Int64 = Swift.Int64()

  /// Maximum number of tokens that can be consumed during the specified
  /// duration. Client application developers can override the default limit up
  /// to this maximum. If specified, this value cannot be set to a value less
  /// than the default limit. If not specified, it is set to the default limit.
  ///
  /// To allow clients to apply overrides with no upper bound, set this to -1,
  /// indicating unlimited maximum quota.
  ///
  /// Used by group-based quotas only.
  public var maxLimit: Swift.Int64 = Swift.Int64()

  /// Free tier value displayed in the Developers Console for this limit.
  /// The free tier is the number of tokens that will be subtracted from the
  /// billed amount when billing is enabled.
  /// This field can only be set on a limit with duration "1d", in a billable
  /// group; it is invalid on any other limit. If this field is not set, it
  /// defaults to 0, indicating that there is no free tier for this service.
  ///
  /// Used by group-based quotas only.
  public var freeTier: Swift.Int64 = Swift.Int64()

  /// Duration of this limit in textual notation. Must be "100s" or "1d".
  ///
  /// Used by group-based quotas only.
  public var duration: Swift.String = Swift.String()

  /// The name of the metric this quota limit applies to. The quota limits with
  /// the same metric will be checked together during runtime. The metric must be
  /// defined within the service config.
  public var metric: Swift.String = Swift.String()

  /// Specify the unit of the quota limit. It uses the same syntax as
  /// [MetricDescriptor.unit][google.api.MetricDescriptor.unit]. The supported
  /// unit kinds are determined by the quota backend system.
  ///
  /// Here are some examples:
  /// * "1/min/{project}" for quota per minute per project.
  ///
  /// Note: the order of unit components is insignificant.
  /// The "1" at the beginning is required to follow the metric unit syntax.
  ///
  /// [google.api.MetricDescriptor.unit]: <doc:MetricDescriptor/unit>
  public var unit: Swift.String = Swift.String()

  /// Tiered limit values. You must specify this as a key:value pair, with an
  /// integer value that is the maximum number of requests allowed for the
  /// specified unit. Currently only STANDARD is supported.
  public var values: [Swift.String: Swift.Int64] = [:]

  /// User-visible display name for this limit.
  /// Optional. If not set, the UI will provide a default display name based on
  /// the quota configuration. This field can be used to override the default
  /// display name generated from the configuration.
  public var displayName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `QuotaLimit`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QuotaLimit().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let defaultLimit = CodingKeys(stringValue: "defaultLimit")
    static let maxLimit = CodingKeys(stringValue: "maxLimit")
    static let freeTier = CodingKeys(stringValue: "freeTier")
    static let duration = CodingKeys(stringValue: "duration")
    static let metric = CodingKeys(stringValue: "metric")
    static let unit = CodingKeys(stringValue: "unit")
    static let values = CodingKeys(stringValue: "values")
    static let displayName = CodingKeys(stringValue: "displayName")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "defaultLimit",
      "maxLimit",
      "freeTier",
      "duration",
      "metric",
      "unit",
      "values",
      "displayName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .defaultLimit) {
      self.defaultLimit = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .maxLimit) {
      self.maxLimit = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .freeTier) {
      self.freeTier = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .duration) {
      self.duration = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .metric) {
      self.metric = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .unit) {
      self.unit = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.Int64].self, forKey: .values)
    {
      self.values = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.defaultLimit, forKey: .defaultLimit)
    try container.encode(self.maxLimit, forKey: .maxLimit)
    try container.encode(self.freeTier, forKey: .freeTier)
    try container.encode(self.duration, forKey: .duration)
    try container.encode(self.metric, forKey: .metric)
    try container.encode(self.unit, forKey: .unit)
    try container.encode(self.values, forKey: .values)
    try container.encode(self.displayName, forKey: .displayName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.QuotaLimit"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
