// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Defines a proto annotation that describes a string field that refers to
/// an API resource.
public struct ResourceReference: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource type that the annotated field references.
  ///
  /// Example:
  ///
  ///     message Subscription {
  ///       string topic = 2 [(google.api.resource_reference) = {
  ///         type: "pubsub.googleapis.com/Topic"
  ///       }];
  ///     }
  ///
  /// Occasionally, a field may reference an arbitrary resource. In this case,
  /// APIs use the special value * in their resource reference.
  ///
  /// Example:
  ///
  ///     message GetIamPolicyRequest {
  ///       string resource = 2 [(google.api.resource_reference) = {
  ///         type: "*"
  ///       }];
  ///     }
  public var type: Swift.String = Swift.String()

  /// The resource type of a child collection that the annotated field
  /// references. This is useful for annotating the `parent` field that
  /// doesn't have a fixed resource type.
  ///
  /// Example:
  ///
  ///     message ListLogEntriesRequest {
  ///       string parent = 1 [(google.api.resource_reference) = {
  ///         child_type: "logging.googleapis.com/LogEntry"
  ///       };
  ///     }
  public var childType: Swift.String = Swift.String()

  /// Initialize a new instance of `ResourceReference`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceReference().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.api.ResourceReference"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
