// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A projection from an input message to the GRPC or REST header.
public struct RoutingParameter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A request field to extract the header key-value pair from.
  public var field: Swift.String = Swift.String()

  /// A pattern matching the key-value field. Optional.
  /// If not specified, the whole field specified in the `field` field will be
  /// taken as value, and its name used as key. If specified, it MUST contain
  /// exactly one named segment (along with any number of unnamed segments) The
  /// pattern will be matched over the field specified in the `field` field, then
  /// if the match is successful:
  /// - the name of the single named segment will be used as a header name,
  /// - the match value of the segment will be used as a header value;
  /// if the match is NOT successful, nothing will be sent.
  ///
  /// Example:
  ///
  ///               -- This is a field in the request message
  ///              |   that the header value will be extracted from.
  ///              |
  ///              |                     -- This is the key name in the
  ///              |                    |   routing header.
  ///              V                    |
  ///     field: "table_name"           v
  ///     path_template: "projects/*/{table_location=instances/*}/tables/*"
  ///                                                ^            ^
  ///                                                |            |
  ///       In the {} brackets is the pattern that --             |
  ///       specifies what to extract from the                    |
  ///       field as a value to be sent.                          |
  ///                                                             |
  ///      The string in the field must match the whole pattern --
  ///      before brackets, inside brackets, after brackets.
  ///
  /// When looking at this specific example, we can see that:
  /// - A key-value pair with the key `table_location`
  ///   and the value matching `instances/*` should be added
  ///   to the x-goog-request-params routing header.
  /// - The value is extracted from the request message's `table_name` field
  ///   if it matches the full pattern specified:
  ///   `projects/*/instances/*/tables/*`.
  ///
  /// **NB:** If the `path_template` field is not provided, the key name is
  /// equal to the field name, and the whole field should be sent as a value.
  /// This makes the pattern for the field and the value functionally equivalent
  /// to `**`, and the configuration
  ///
  ///     {
  ///       field: "table_name"
  ///     }
  ///
  /// is a functionally equivalent shorthand to:
  ///
  ///     {
  ///       field: "table_name"
  ///       path_template: "{table_name=**}"
  ///     }
  ///
  /// See Example 1 for more details.
  public var pathTemplate: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RoutingParameter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RoutingParameter().with { $0.field = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let field = CodingKeys(stringValue: "field")
    static let pathTemplate = CodingKeys(stringValue: "pathTemplate")

    static let _knownKeys: Set<Swift.String> = [
      "field",
      "pathTemplate",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .field) {
      self.field = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pathTemplate) {
      self.pathTemplate = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.field, forKey: .field)
    try container.encode(self.pathTemplate, forKey: .pathTemplate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.RoutingParameter"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
