// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Define a parameter's name and location. The parameter may be passed as either
/// an HTTP header or a URL query parameter, and if both are passed the behavior
/// is implementation-dependent.
public struct SystemParameter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Define the name of the parameter, such as "api_key" . It is case sensitive.
  public var name: Swift.String

  /// Define the HTTP header name to use for the parameter. It is case
  /// insensitive.
  public var httpHeader: Swift.String

  /// Define the URL query parameter name to use for the parameter. It is case
  /// sensitive.
  public var urlQueryParameter: Swift.String

  /// Initialize a new instance of `SystemParameter`.
  public init(
    name: Swift.String = Swift.String(),
    httpHeader: Swift.String = Swift.String(),
    urlQueryParameter: Swift.String = Swift.String(),
  ) {
    self.name = name
    self.httpHeader = httpHeader
    self.urlQueryParameter = urlQueryParameter
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.api.SystemParameter" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
