// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Usage configuration rules for the service.
public struct UsageRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Selects the methods to which this rule applies. Use '*' to indicate all
  /// methods in all APIs.
  ///
  /// Refer to [selector][google.api.DocumentationRule.selector] for syntax
  /// details.
  ///
  /// [google.api.DocumentationRule.selector]: <doc:DocumentationRule/selector>
  public var selector: Swift.String = Swift.String()

  /// Use this rule to configure unregistered calls for the service. Unregistered
  /// calls are calls that do not contain consumer project identity.
  /// (Example: calls that do not contain an API key).
  ///
  /// WARNING: By default, API methods do not allow unregistered calls, and each
  /// method call must be identified by a consumer project identity.
  public var allowUnregisteredCalls: Swift.Bool = Swift.Bool()

  /// If true, the selected method should skip service control and the control
  /// plane features, such as quota and billing, will not be available.
  /// This flag is used by Google Cloud Endpoints to bypass checks for internal
  /// methods, such as service health check methods.
  public var skipServiceControl: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `UsageRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UsageRule().with { $0.selector = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.api.UsageRule" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
