// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A visibility rule provides visibility configuration for an individual API
/// element.
public struct VisibilityRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Selects methods, messages, fields, enums, etc. to which this rule applies.
  ///
  /// Refer to [selector][google.api.DocumentationRule.selector] for syntax
  /// details.
  ///
  /// [google.api.DocumentationRule.selector]: <doc:DocumentationRule/selector>
  public var selector: Swift.String

  /// A comma-separated list of visibility labels that apply to the `selector`.
  /// Any of the listed labels can be used to grant the visibility.
  ///
  /// If a rule has multiple labels, removing one of the labels but not all of
  /// them can break clients.
  ///
  /// Example:
  ///
  ///     visibility:
  ///       rules:
  ///       - selector: google.calendar.Calendar.EnhancedSearch
  ///         restriction: INTERNAL, PREVIEW
  ///
  /// Removing INTERNAL from this restriction will break clients that rely on
  /// this method and only had access to it through INTERNAL.
  public var restriction: Swift.String

  /// Initialize a new instance of `VisibilityRule`.
  public init(
    selector: Swift.String = Swift.String(),
    restriction: Swift.String = Swift.String(),
  ) {
    self.selector = selector
    self.restriction = restriction
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.api.VisibilityRule" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
